normlz<-function(h,...){
	f<-function(h,...){
		x<<-svalue(h$obj)
		}
		try(({
		datAffy<-datAffy;datAgOne<-datAgOne;datAgTwo<-datAgTwo;datIllBA<-datIllBA;
		lumi_data<-lumi_data;data.matrix_Nimblegen<-data.matrix_Nimblegen;
		data.matrixImp<-data.matrixImp;data.matrix_onlineImp<-data.matrix_onlineImp;
		normAffy<-normAffy;normAgOne<-normAgOne;normAgTwo<-normAgTwo;normIl_B<-normIl_B;normIl_L<-normIl_L;
		normNimblg<-normNimblg;normDmsm<-normDmsm;normDmo<-normDmo;
		}),silent=TRUE)

	if(length(normAffy)!=0)
	{
		if (!requireNamespace("affy", quietly = TRUE))
		{
			install.packages("affy")
		} else {
			library(affy)
		}

		setwd(folder_Affy)	
		svalue(sb)<-"				Please wait while Normalizing.."
		dat2Affy<<-justRMA()
		dat2Affy.m<<-exprs(dat2Affy)
		dat2Affy.m<<-as.matrix(dat2Affy.m)
		rownames(dat2Affy.m)<<-as.character(rownames(dat2Affy.m))
		try(if(length(rownames(dat2Affy.m))==0)rownames(dat2Affy.m)<<-1:length(dat2Affy.m[,1]),silent=TRUE)
		if(length(dat2Affy.m)==0)gmessage("Could not Normalize this type of data..!\n",title="Analysis",icon="error")
		if(length(dat2Affy.m)!=0){	

			delete(g1,g1_1)
			l$Affymetrix$Normalization<<-list()
			g1_1<<-ggroup(container=g1,visible=FALSE)
			tr<<-gtree(offspring=tree,container=g1_1)
			size(tr)<-c(300,480)
			visible(g1_1)<-TRUE
			}
			display()
		svalue(sb)<-"Done"
		on.exit(setwd(cur_dir))	
		normAffy=NULL
	}
	if(length(normAgOne)!=0)
	{
		setwd(folder_Ag1)	
		norm_xx=NULL
		norm_methods=c("none","scale","quantile","cyclicloess")
		norm_w<<-gwindow("Methods",width=300,height=150)
		norm_gp<-ggroup(container=norm_w,horizontal=FALSE)
		norm_x<-gtable(norm_methods,chosencol=1,container=norm_gp)
		size(norm_x)=c(200,120)
		norm_gp2<-ggroup(container=norm_gp,width=30,height=15)
		addHandlerChanged(norm_x,handler=function(h,...){
			norm_x2<-svalue(h$obj)
			print(norm_x2)
			norm_xx<<-norm_x2
			print(norm_xx)
			}
		)
		addSpring(norm_gp2)
		norm_y<-gbutton("CANCEL",handler=function(h,...){
			dispose(norm_w)
			},container=norm_gp2,anchor=c(1,-1)
		)
		norm_y2<-gbutton("OK",handler=function(h,...){
			dispose(norm_w)
			svalue(sb)<-"				Please wait while Normalizing.."
			datAgOne2=NULL
			try(datAgOne2<<-backgroundCorrect(datAgOne,"normexp"),silent=TRUE)
			if(length(datAgOne2)==0)datAgOne2<-datAgOne
			print(norm_xx)
			datAgOne2<-normalizeBetweenArrays(datAgOne2$R,method=norm_xx)
			datAgOne2<-log(datAgOne2)
			datAgOne2.m<<-datAgOne2
			datAgOne2.m<<-as.matrix(datAgOne2.m)
			rownames(datAgOne2.m)<<-as.character(rownames(datAgOne2.m))
			try(if(length(rownames(datAgOne2.m))==0)rownames(datAgOne2.m)<<-1:length(datAgOne2.m[,1]),silent=TRUE)
			if(length(datAgOne2.m)==0)gmessage("Could not Normalize this type of data..!\n",title="Analysis",icon="error")
			if(length(datAgOne2.m)!=0){
				delete(g1,g1_1)
				l$Agilent_OneColor$Normalization<<-list()
				g1_1<<-ggroup(container=g1)
				tr<<-gtree(offspring=tree,container=g1_1)
				size(tr)<-c(300,480)
				}
			display()
			svalue(sb)<-"Done"
			},container=norm_gp2,anchor=c(1,-1)
		)
		on.exit(setwd(cur_dir))	
		normAgOne=NULL
	}
	if(length(normAgTwo)!=0)
	{
		setwd(folder_Ag2)	
		norm_xx=NULL
		norm_methods=c("none","median","loess","printtiploess","composite","control","robustspline")
		norm_w<-gwindow("Methods",width=300,height=300)
		norm_gp<-ggroup(container=norm_w,horizontal=FALSE)
		norm_x<-gtable(norm_methods,chosencol=1,container=norm_gp)
		size(norm_x)=c(200,250)
		norm_gp2<-ggroup(container=norm_gp,width=30,height=15)
		addHandlerChanged(norm_x,handler=function(h,...){
			norm_x2<-svalue(h$obj)
			norm_xx<<-norm_x2
			}
		)
		addSpring(norm_gp2)
		norm_y<-gbutton("CANCEL",handler=function(h,...){
			dispose(norm_w)
			},container=norm_gp2,anchor=c(1,-1)
		)
		norm_y2<-gbutton("OK",handler=function(h,...){
			dispose(norm_w)
			svalue(sb)<-"				Please wait while Normalizing.."
			datAgTwo2<<-normalizeWithinArrays(datAgTwo,method=norm_xx,"normexp")
			datAgTwo2.m<<-datAgTwo2$M
			rownames(datAgTwo2.m)<<-datAgTwo2$genes$ProbeName
			datAgTwo2.m<<-as.matrix(datAgTwo2.m)
			rownames(datAgTwo2.m)<<-as.character(rownames(datAgTwo2.m))
			try(if(length(rownames(datAgTwo2.m))==0)rownames(datAgTwo2.m)<<-1:length(datAgTwo2.m[,1]),silent=TRUE)
			if(length(datAgTwo2.m)==0)gmessage("Could not Normalize this type of data..!\n",title="Analysis",icon="error")
			if(length(datAgTwo2.m)!=0){
				delete(g1,g1_1)
				l$Agilent_TwoColor$Normalization<<-list()
				g1_1<<-ggroup(container=g1)
				tr<<-gtree(offspring=tree,container=g1_1)
				size(tr)<-c(300,480)
				}
			display()
			svalue(sb)<-"Done"
			},container=norm_gp2,anchor=c(1,-1)
		)
		on.exit(setwd(cur_dir))	
		normAgTwo=NULL
	}
	if(length(normIl_B)!=0)
	{
		if (!requireNamespace("beadarray", quietly = TRUE))
		{
			install.packages("beadarray")
		} else {
			library(beadarray)
		}
		setwd(folder_Il_B)	
		norm_xx=NULL
		norm_methods=c("quantile","qspline","vsn","rankInvariant","median","none","nesq","rsn")
		norm_w<-gwindow("Methods",width=300,height=200)
		norm_gp<-ggroup(container=norm_w,horizontal=FALSE)
		norm_x<-gtable(norm_methods,chosencol=1,container=norm_gp)
		size(norm_x)=c(200,160)
		norm_gp2<-ggroup(container=norm_gp,width=30,height=15)
		addHandlerChanged(norm_x,handler=function(h,...){
			norm_x2<-svalue(h$obj)
			norm_xx<<-norm_x2
			}
		)
		addSpring(norm_gp2)
		norm_y<-gbutton("CANCEL",handler=function(h,...){
			dispose(norm_w)
			},container=norm_gp2,anchor=c(1,-1)
		)
		norm_y2<-gbutton("OK",handler=function(h,...){
			dispose(norm_w)
			svalue(sb)<-"				Please wait while Normalizing.."
			datIllBA2<-normaliseIllumina(datIllBA,method=norm_xx)
			datIllBA2.m<-exprs(datIllBA2)
			datIllBA2.m2<<-log2(datIllBA2.m)
			datIllBA2.m2<<-as.matrix(datIllBA2.m2)
			rownames(datIllBA2.m2)<<-as.character(rownames(datIllBA2.m2))
			try(if(length(rownames(datIllBA2.m2))==0)rownames(datIllBA2.m2)<<-1:length(datIllBA2.m2[,1]),silent=TRUE)
			if(length(datIllBA2.m)==0)gmessage("Could not Normalize this type of data..!\n",title="Analysis",icon="error")
			if(length(datIllBA2.m)!=0){
				delete(g1,g1_1)
				l$Illumina_Beadarray$Normalization<<-list()
				g1_1<<-ggroup(container=g1)
				tr<<-gtree(offspring=tree,container=g1_1)
				size(tr)<-c(300,480)
				}
			display()
			svalue(sb)<-"Done"
			},container=norm_gp2,anchor=c(1,-1)
		)
		on.exit(setwd(cur_dir))	
		normIl_B=NULL
	}
	if(length(normIl_L)!=0)
	{
		if (!requireNamespace("lumi", quietly = TRUE))
		{
			install.packages("lumi")
		} else {
			library(lumi)
		}
		setwd(folder_Il_L)	
		svalue(sb)<-"				Please wait while Normalizing.."
		lumi_NQ<<-lumiExpresso(lumi_data,QC.evaluation=TRUE)
		summary(lumi_NQ,'QC')
		lumi_NQ.m<<-lumi_NQ
		lumi_NQ.m<<-as.matrix(lumi_NQ.m)
		rownames(lumi_NQ.m)<<-as.character(rownames(lumi_NQ.m))
		try(if(length(rownames(lumi_NQ.m))==0)rownames(lumi_NQ.m)<<-1:length(lumi_NQ.m[,1]),silent=TRUE)
		if(length(lumi_NQ.m)==0)gmessage("Could not Normalize this type of data..!\n",title="Analysis",icon="error")
		if(length(lumi_NQ.m)!=0){
			delete(g1,g1_1)
			l$Illumina_Lumi$Normalization<<-list()
			g1_1<<-ggroup(container=g1)
			tr<<-gtree(offspring=tree,container=g1_1)
			size(tr)<-c(300,480)
			}
		display()
		svalue(sb)<-"Done"
		on.exit(setwd(cur_dir))	
		normIl_L=NULL
	}
	if(length(normNimblg)!=0)
	{
		setwd(folder_N)	
		norm_xx=NULL
		norm_methods=c("none","scale","quantile","cyclicloess")
		norm_w<-gwindow("Methods",width=300,height=150)
		norm_gp<-ggroup(container=norm_w,horizontal=FALSE)
		norm_x<-gtable(norm_methods,chosencol=1,container=norm_gp)
		size(norm_x)=c(200,120)
		norm_gp2<-ggroup(container=norm_gp,width=30,height=15)
		addHandlerChanged(norm_x,handler=function(h,...){
			norm_x2<-svalue(h$obj)
			norm_xx<<-norm_x2
			}
		)
		addSpring(norm_gp2)
		norm_y<-gbutton("CANCEL",handler=function(h,...){
			dispose(norm_w)
			},container=norm_gp2,anchor=c(1,-1)
		)
		norm_y2<-gbutton("OK",handler=function(h,...){
			dispose(norm_w)
			svalue(sb)<-"				Please wait while Normalizing.."
			data.matrix_Nimblegen2<<-normalizeBetweenArrays(data.matrix_Nimblegen,method=norm_xx)
			data.matrix_Nimblegen2.m<<-data.matrix_Nimblegen2
			data.matrix_Nimblegen2.m<<-as.matrix(data.matrix_Nimblegen2.m)
			rownames(data.matrix_Nimblegen2.m)<<-as.character(rownames(data.matrix_Nimblegen2.m))
			try(if(length(rownames(data.matrix_Nimblegen2.m))==0)rownames(data.matrix_Nimblegen2.m)<<-1:length(data.matrix_Nimblegen2.m[,1]),silent=TRUE)
			if(length(data.matrix_Nimblegen2.m)==0)gmessage("Could not Normalize this type of data..!\n",title="Analysis",icon="error")
			if(length(data.matrix_Nimblegen2.m)!=0){
				delete(g1,g1_1)
				l$Nimblegen$Normalization<<-list()
				g1_1<<-ggroup(container=g1)
				tr<<-gtree(offspring=tree,container=g1_1)
				size(tr)<-c(300,480)
				}
			display()
			svalue(sb)<-"Done"
			},container=norm_gp2,anchor=c(1,-1)
		)
		on.exit(setwd(cur_dir))	
		normNimblg=NULL
	}
	if(length(normDmsm)!=0)
	{
		setwd(folder_S)	
		norm_xx=NULL
		norm_methods=c("none","scale","quantile","cyclicloess")
		norm_w<-gwindow("Methods",width=300,height=150)
		norm_gp<-ggroup(container=norm_w,horizontal=FALSE)
		norm_x<-gtable(norm_methods,chosencol=1,container=norm_gp)
		size(norm_x)=c(200,120)
		norm_gp2<-ggroup(container=norm_gp,width=30,height=15)
		addHandlerChanged(norm_x,handler=function(h,...){
			norm_x2<-svalue(h$obj)
			norm_xx<<-norm_x2
			}
		)
		addSpring(norm_gp2)
		norm_y<-gbutton("CANCEL",handler=function(h,...){
			dispose(norm_w)
			},container=norm_gp2,anchor=c(1,-1)
		)
		norm_y2<-gbutton("OK",handler=function(h,...){
			dispose(norm_w)
			svalue(sb)<-"				Please wait while Normalizing.."
			data.matrixNorm<-normalizeBetweenArrays(data.matrixImp,method=norm_xx)
			tmp<-aggregate(data.matrixNorm,list(rownames(data.matrixNorm)),median)
			data.matrixNorm<<-as.matrix(tmp[,-1])
			rownames(data.matrixNorm)<<-tmp[,1]
			data.matrixNorm.m<<-data.matrixNorm
			data.matrixNorm.m<<-as.matrix(data.matrixNorm.m)
			try(if(length(rownames(data.matrixNorm.m))==0)rownames(data.matrixNorm.m)<<-1:length(data.matrixNorm.m[,1]),silent=TRUE)
			if(length(data.matrixNorm.m)==0)gmessage("Could not Normalize this type of data..!\n",title="Analysis",icon="error")
			if(length(data.matrixNorm.m)!=0){
				delete(g1,g1_1)
				l$Series_Matrix$Normalization<<-list()
				g1_1<<-ggroup(container=g1)
				tr<<-gtree(offspring=tree,container=g1_1)
				size(tr)<-c(300,480)
				}
			display()
			svalue(sb)<-"Done"
			},container=norm_gp2,anchor=c(1,-1)
		)
		on.exit(setwd(cur_dir))	
		normDmsm=NULL
	}
	if(length(normDmo)!=0)
	{
		norm_xx=NULL
		norm_methods=c("none","scale","quantile","cyclicloess")
		norm_w<-gwindow("Methods",width=300,height=150)
		norm_gp<-ggroup(container=norm_w,horizontal=FALSE)
		norm_x<-gtable(norm_methods,chosencol=1,container=norm_gp)
		size(norm_x)=c(200,120)
		norm_gp2<-ggroup(container=norm_gp,width=30,height=15)
		addHandlerChanged(norm_x,handler=function(h,...){
			norm_x2<-svalue(h$obj)
			norm_xx<<-norm_x2
			}
		)
		addSpring(norm_gp2)
		norm_y<-gbutton("CANCEL",handler=function(h,...){
			dispose(norm_w)
			},container=norm_gp2,anchor=c(1,-1)
		)
		norm_y2<-gbutton("OK",handler=function(h,...){
			dispose(norm_w)
			svalue(sb)<-"				Please wait while Normalizing.."
			data.matrix_onlineNorm<-normalizeBetweenArrays(data.matrix_onlineImp,method=norm_xx)
			tmp<-aggregate(data.matrix_onlineNorm,list(rownames(data.matrix_onlineNorm)),median)
			data.matrix_onlineNorm<-as.matrix(tmp[,-1])
			rownames(data.matrix_onlineNorm)<<-tmp[,1]
			data.matrix_onlineNorm.m<<-data.matrix_onlineNorm
			data.matrix_onlineNorm.m<<-as.matrix(data.matrix_onlineNorm.m)
			rownames(data.matrix_onlineNorm.m)<<-as.character(rownames(data.matrix_onlineNorm.m))
			try(if(length(rownames(data.matrix_onlineNorm.m))==0)rownames(data.matrix_onlineNorm.m)<<-1:length(data.matrix_onlineNorm.m[,1]),silent=TRUE)
			if(length(data.matrix_onlineNorm.m)==0)gmessage("Could not Normalize this type of data..!\n",title="Analysis",icon="error")
			if(length(data.matrix_onlineNorm.m)!=0){
				delete(g1,g1_1)
				l$Online_Data$Normalization<<-list()
				g1_1<<-ggroup(container=g1)
				tr<<-gtree(offspring=tree,container=g1_1)
				size(tr)<-c(300,480)
				}
			display()
			svalue(sb)<-"Done"
				},container=norm_gp2,anchor=c(1,-1)
		)
		on.exit(setwd(cur_dir))	
		normDmo=NULL
	}
}

normlz()
