graph_gsea_goBP<-function(h,...){
	try(({GOresultBP_Affy<-GOresultBP_Affy;GOresultBP_Ag1<-GOresultBP_Ag1;GOresultBP_Ag2<-GOresultBP_Ag2;
		GOresultBP_Il_B<-GOresultBP_Il_B;GOresultBP_Il_L<-GOresultBP_Il_L;GOresultBP_N<-GOresultBP_N;
		GOresultBP_S<-GOresultBP_S;GOresultBP_O<-GOresultBP_O;g1_1<-g1_1;l<-l;tree<-tree;
	}),silent=TRUE)
	platforms=NULL;
	aa=0;bb=0;cc=0;dd=0;ee=0;ff=0;gg=0;hh=0;
	try(({
		if(exists("GOresultBP_Affy"))aa=length(GOresultBP_Affy)
		if(exists("GOresultBP_Ag1"))bb=length(GOresultBP_Ag1)
		if(exists("GOresultBP_Ag2"))cc=length(GOresultBP_Ag2)
		if(exists("GOresultBP_Il_B"))dd=length(GOresultBP_Il_B)
		if(exists("GOresultBP_Il_L"))ee=length(GOresultBP_Il_L)
		if(exists("GOresultBP_N"))ff=length(GOresultBP_N)
		if(exists("GOresultBP_S"))gg=length(GOresultBP_S)
		if(exists("GOresultBP_O"))hh=length(GOresultBP_O)
		}),silent=TRUE)
	if(aa!=0)platforms=c(platforms,"Affymetrix")
	if(bb!=0)platforms=c(platforms,"Agilent_OneColor")
	if(cc!=0)platforms=c(platforms,"Agilent_TwoColor")
	if(dd!=0)platforms=c(platforms,"Illumina_Beadarray")
	if(ee!=0)platforms=c(platforms,"Illumina_Lumi")
	if(ff!=0)platforms=c(platforms,"Nimblegen")
	if(gg!=0)platforms=c(platforms,"Series_Matrix")
	if(hh!=0)platforms=c(platforms,"Online_Data")

	graph_gsea_goBP_Affy=NULL;graph_gsea_goBP_Ag1=NULL;graph_gsea_goBP_Ag2=NULL;graph_gsea_goBP_Il_B=NULL;graph_gsea_goBP_Il_L=NULL;
	graph_gsea_goBP_N=NULL;graph_gsea_goBP_S=NULL;graph_gsea_goBP_O=NULL;
	legend_gsea_goBP_Affy=NULL;legend_gsea_goBP_Ag1=NULL;legend_gsea_goBP_Ag2=NULL;legend_gsea_goBP_Il_B=NULL;legend_gsea_goBP_Il_L=NULL;
	legend_gsea_goBP_N=NULL;legend_gsea_goBP_S=NULL;legend_gsea_goBP_O=NULL;p_v=NULL;view_ww=NULL;
	nodefill_gsea_goBP_Affy=NULL;g_gsea_goBP_Affy=NULL;nodefill_gsea_goBP_Ag1=NULL;g_gsea_goBP_Ag1=NULL;
	nodefill_gsea_goBP_Ag2=NULL;g_gsea_goBP_Ag2=NULL;nodefill_gsea_goBP_Il_B=NULL;g_gsea_goBP_Il_B=NULL;
	nodefill_gsea_goBP_Il_L=NULL;g_gsea_goBP_Il_L=NULL;nodefill_gsea_goBP_N=NULL;g_gsea_goBP_N=NULL;
	nodefill_gsea_goBP_S=NULL;g_gsea_goBP_S=NULL;nodefill_gsea_goBP_O=NULL;g_gsea_goBP_O=NULL;

	rm(graph_gsea_goBP_Affy,graph_gsea_goBP_Ag1,graph_gsea_goBP_Ag2,graph_gsea_goBP_Il_B,graph_gsea_goBP_Il_L,
	graph_gsea_goBP_N,graph_gsea_goBP_S,graph_gsea_goBP_O,
	nodefill_gsea_goBP_Affy,g_gsea_goBP_Affy,nodefill_gsea_goBP_Ag1,g_gsea_goBP_Ag1,
	nodefill_gsea_goBP_Ag2,g_gsea_goBP_Ag2,nodefill_gsea_goBP_Il_B,g_gsea_goBP_Il_B,
	nodefill_gsea_goBP_Il_L,g_gsea_goBP_Il_L,nodefill_gsea_goBP_N,g_gsea_goBP_N,
	nodefill_gsea_goBP_S,g_gsea_goBP_S,nodefill_gsea_goBP_O,g_gsea_goBP_O,
	legend_gsea_goBP_Affy,legend_gsea_goBP_Ag1,legend_gsea_goBP_Ag2,legend_gsea_goBP_Il_B,legend_gsea_goBP_Il_L,
	legend_gsea_goBP_N,legend_gsea_goBP_S,legend_gsea_goBP_O,p_v,view_ww)

	x=NULL
	f<-function(h,...){
		x<<-svalue(h$obj)
		}
	z=NULL
	p_value=c(0.0000001,0.000001,0.00001,0.0001,0.001,0.01,0.05,0.1,0.5,1)
	w_gsea<-gwindow("Select p-value",horizontal=FALSE,height=100,width=100)
	gp_gsea<-ggroup(container=w_gsea,horizontal=FALSE)
	glabel("p-value",container=gp_gsea)
	cb_gsea<-gcombobox(p_value,editable=TRUE,selected=7,container=gp_gsea,handler=function(h,...){
		z<-svalue(h$obj)
		p_v<<-as.numeric(z)
	}
	)

	gp_gsea2<-ggroup(container=w_gsea)
	gbutton("CANCEL",border=TRUE,handler=function(h,...){
		p_v<<-0.05
		svalue(sb)<-"Done"
		dispose(w_gsea)
	},container=gp_gsea2,anchor=c(1,-1))
	gbutton("OK",border=TRUE,handler=function(h,...){
		z<-svalue(cb_gsea)
		p_v<<-as.numeric(z)
		dispose(w_gsea)
		svalue(sb)<-"				Please wait while Graphs.."
		w_dge<-gwindow("Select your data",width=260,height=280,visible=FALSE,horizontal=FALSE)
		gp_dge<-ggroup(container=w_dge,horizontal=FALSE)
		cbg_dge<-gcheckboxgroup(platforms,container=gp_dge,handler=f)
		svalue(cbg_dge,index=FALSE)<-1:8
		gp2_dge<-ggroup(container=gp_dge,width=30,height=15,horizontal=TRUE)
		addSpring(gp2_dge)
		y<-gbutton("CANCEL",border=TRUE,handler=function(h,...){
			dispose(w_dge)
		},container=gp2_dge,anchor=c(1,-1))
		y2<-gbutton("OK",border=TRUE,handler=function(h,...){
			if(length(x)!=0){
				dispose(w_dge)
				if(length(which(x=="Affymetrix"))!=0)
				{
					try(dispose(view_ww),silent=TRUE)
					GO.vec<-rownames(GOresultBP_Affy)[GOresultBP_Affy$Pvalue<=p_v]
					g<-GOGraph(GO.vec,GOBPPARENTS)
					g<-removeNode("all",g)
					nodes<-buildNodeList(g)
					focusnode<-sapply(nodes,name) %in% GO.vec
					names(focusnode)<-names(nodes)
					nodefill<-ifelse(focusnode,"yellow","white")
					nodefill_gsea_goBP_Affy<<-nodefill
					g_gsea_goBP_Affy<<-g
					nAttrs<-list()
					nAttrs$fillcolor<-nodefill
					graph_gsea_goBP_Affy<<-plot(g,nodeAttrs=nAttrs)
					terms<-getGOTerm(nodes(g))
					legend<-data.frame(terms)
					legend_gsea_goBP_Affy<<-data.frame(rownames(legend),legend)
					colnames(legend_gsea_goBP_Affy)<<-c("Identifier","BP")
					view_ww<<-gwindow("Graph_Legend",visible=FALSE,height=400,width=600)
					gtable(legend_gsea_goBP_Affy,container=view_ww)
					visible(view_ww)<<-TRUE
					if(length(graph_gsea_goBP_Affy)!=0){
						visible(g1_1)<-FALSE
						l$Affymetrix$Graph_GSEA_GO$BP<<-list()
						tr<<-gtree(offspring=tree,container=g1_1)
						size(tr)<-c(300,400)
						visible(g1_1)<-TRUE
					}
					display()	
				}
				if(length(which(x=="Agilent_OneColor"))!=0)
				{
					try(dispose(view_ww),silent=TRUE)
					GO.vec<-rownames(GOresultBP_Ag1)[GOresultBP_Ag1$Pvalue<=p_v]
					g<-GOGraph(GO.vec,GOBPPARENTS)
					g<-removeNode("all",g)
					nodes<-buildNodeList(g)
					focusnode<-sapply(nodes,name) %in% GO.vec
					names(focusnode)<-names(nodes)
					nodefill<-ifelse(focusnode,"yellow","white")
					nodefill_gsea_goBP_Ag1<<-nodefill
					g_gsea_goBP_Ag1<<-g
					nAttrs<-list()
					nAttrs$fillcolor<-nodefill
					graph_gsea_goBP_Ag1<<-plot(g,nodeAttrs=nAttrs)
					terms<-getGOTerm(nodes(g))
					legend<-data.frame(terms)
					legend_gsea_goBP_Ag1<<-data.frame(rownames(legend),legend)
					colnames(legend_gsea_goBP_Ag1)<<-c("Identifier","BP")
					view_ww<<-gwindow("Graph_Legend",visible=FALSE,height=400,width=600)
					gtable(legend_gsea_goBP_Ag1,container=view_ww)
					visible(view_ww)<<-TRUE
					if(length(graph_gsea_goBP_Ag1)!=0){
						visible(g1_1)<-FALSE
						l$Agilent_OneColor$Graph_GSEA_GO$BP<<-list()
						tr<<-gtree(offspring=tree,container=g1_1)
						size(tr)<-c(300,400)
						visible(g1_1)<-TRUE
					}
					display()	
				}
				if(length(which(x=="Agilent_TwoColor"))!=0)
				{
					try(dispose(view_ww),silent=TRUE)
					GO.vec<-rownames(GOresultBP_Ag2)[GOresultBP_Ag2$Pvalue<=p_v]
					g<-GOGraph(GO.vec,GOBPPARENTS)
					g<-removeNode("all",g)
					nodes<-buildNodeList(g)
					focusnode<-sapply(nodes,name) %in% GO.vec
					names(focusnode)<-names(nodes)
					nodefill<-ifelse(focusnode,"yellow","white")
					nodefill_gsea_goBP_Ag2<<-nodefill
					g_gsea_goBP_Ag2<<-g
					nAttrs<-list()
					nAttrs$fillcolor<-nodefill
					graph_gsea_goBP_Ag2<<-plot(g,nodeAttrs=nAttrs)
					terms<-getGOTerm(nodes(g))
					legend<-data.frame(terms)
					legend_gsea_goBP_Ag2<<-data.frame(rownames(legend),legend)
					colnames(legend_gsea_goBP_Ag2)<<-c("Identifier","BP")
					view_ww<<-gwindow("Graph_Legend",visible=FALSE,height=400,width=600)
					gtable(legend_gsea_goBP_Ag2,container=view_ww)
					visible(view_ww)<<-TRUE
					if(length(graph_gsea_goBP_Ag2)!=0){
						visible(g1_1)<-FALSE
						l$Agilent_TwoColor$Graph_GSEA_GO$BP<<-list()
						tr<<-gtree(offspring=tree,container=g1_1)
						size(tr)<-c(300,400)
						visible(g1_1)<-TRUE
					}
					display()	
				}
				if(length(which(x=="Illumina_Beadarray"))!=0)
				{
					try(dispose(view_ww),silent=TRUE)
					GO.vec<-rownames(GOresultBP_Il_B)[GOresultBP_Il_B$Pvalue<=p_v]
					g<-GOGraph(GO.vec,GOBPPARENTS)
					g<-removeNode("all",g)
					nodes<-buildNodeList(g)
					focusnode<-sapply(nodes,name) %in% GO.vec
					names(focusnode)<-names(nodes)
					nodefill<-ifelse(focusnode,"yellow","white")
					nodefill_gsea_goBP_Il_B<<-nodefill
					g_gsea_goBP_Il_B<<-g
					nAttrs<-list()
					nAttrs$fillcolor<-nodefill
					graph_gsea_goBP_Il_B<<-plot(g,nodeAttrs=nAttrs)
					terms<-getGOTerm(nodes(g))
					legend<-data.frame(terms)
					legend_gsea_goBP_Il_B<<-data.frame(rownames(legend),legend)
					colnames(legend_gsea_goBP_Il_B)<<-c("Identifier","BP")
					view_ww<<-gwindow("Graph_Legend",visible=FALSE,height=400,width=600)
					gtable(legend_gsea_goBP_Il_B,container=view_ww)
					visible(view_ww)<<-TRUE
					if(length(graph_gsea_goBP_Il_B)!=0){
						visible(g1_1)<-FALSE
						l$Illumina_Beadarray$Graph_GSEA_GO$BP<<-list()
						tr<<-gtree(offspring=tree,container=g1_1)
						size(tr)<-c(300,400)
						visible(g1_1)<-TRUE
					}
					display()	
				}
				if(length(which(x=="Illumina_Lumi"))!=0)
				{
					try(dispose(view_ww),silent=TRUE)
					GO.vec<-rownames(GOresultBP_Il_L)[GOresultBP_Il_L$Pvalue<=p_v]
					g<-GOGraph(GO.vec,GOBPPARENTS)
					g<-removeNode("all",g)
					nodes<-buildNodeList(g)
					focusnode<-sapply(nodes,name) %in% GO.vec
					names(focusnode)<-names(nodes)
					nodefill<-ifelse(focusnode,"yellow","white")
					nodefill_gsea_goBP_Il_L<<-nodefill
					g_gsea_goBP_Il_L<<-g
					nAttrs<-list()
					nAttrs$fillcolor<-nodefill
					graph_gsea_goBP_Il_L<<-plot(g,nodeAttrs=nAttrs)
					terms<-getGOTerm(nodes(g))
					legend<-data.frame(terms)
					legend_gsea_goBP_Il_L<<-data.frame(rownames(legend),legend)
					colnames(legend_gsea_goBP_Il_L)<<-c("Identifier","BP")
					view_ww<<-gwindow("Graph_Legend",visible=FALSE,height=400,width=600)
					gtable(legend_gsea_goBP_Il_L,container=view_ww)
					visible(view_ww)<<-TRUE
					if(length(graph_gsea_goBP_Il_L)!=0){
						visible(g1_1)<-FALSE
						l$Illumina_Lumi$Graph_GSEA_GO$BP<<-list()
						tr<<-gtree(offspring=tree,container=g1_1)
						size(tr)<-c(300,400)
						visible(g1_1)<-TRUE
					}
					display()	
				}
				if(length(which(x=="Nimblegen"))!=0)
				{
					try(dispose(view_ww),silent=TRUE)
					GO.vec<-rownames(GOresultBP_N)[GOresultBP_N$Pvalue<=p_v]
					g<-GOGraph(GO.vec,GOBPPARENTS)
					g<-removeNode("all",g)
					nodes<-buildNodeList(g)
					focusnode<-sapply(nodes,name) %in% GO.vec
					names(focusnode)<-names(nodes)
					nodefill<-ifelse(focusnode,"yellow","white")
					nodefill_gsea_goBP_N<<-nodefill
					g_gsea_goBP_N<<-g
					nAttrs<-list()
					nAttrs$fillcolor<-nodefill
					graph_gsea_goBP_N<<-plot(g,nodeAttrs=nAttrs)
					terms<-getGOTerm(nodes(g))
					legend<-data.frame(terms)
					legend_gsea_goBP_N<<-data.frame(rownames(legend),legend)
					colnames(legend_gsea_goBP_N)<<-c("Identifier","BP")
					view_ww<<-gwindow("Graph_Legend",visible=FALSE,height=400,width=600)
					gtable(legend_gsea_goBP_N,container=view_ww)
					visible(view_ww)<<-TRUE
					if(length(graph_gsea_goBP_N)!=0){
						visible(g1_1)<-FALSE
						l$Nimblegen$Graph_GSEA_GO$BP<<-list()
						tr<<-gtree(offspring=tree,container=g1_1)
						size(tr)<-c(300,400)
						visible(g1_1)<-TRUE
					}
					display()	
				}
				if(length(which(x=="Series_Matrix"))!=0)
				{
					try(dispose(view_ww),silent=TRUE)
					GO.vec<-rownames(GOresultBP_S)[GOresultBP_S$Pvalue<=p_v]
					g<-GOGraph(GO.vec,GOBPPARENTS)
					g<-removeNode("all",g)
					nodes<-buildNodeList(g)
					focusnode<-sapply(nodes,name) %in% GO.vec
					names(focusnode)<-names(nodes)
					nodefill<-ifelse(focusnode,"yellow","white")
					nodefill_gsea_goBP_S<<-nodefill
					g_gsea_goBP_S<<-g
					nAttrs<-list()
					nAttrs$fillcolor<-nodefill
					graph_gsea_goBP_S<<-plot(g,nodeAttrs=nAttrs)
					terms<-getGOTerm(nodes(g))
					legend<-data.frame(terms)
					legend_gsea_goBP_S<<-data.frame(rownames(legend),legend)
					colnames(legend_gsea_goBP_S)<<-c("Identifier","BP")
					view_ww<<-gwindow("Graph_Legend",visible=FALSE,height=400,width=600)
					gtable(legend_gsea_goBP_S,container=view_ww)
					visible(view_ww)<<-TRUE
					if(length(graph_gsea_goBP_S)!=0){
						visible(g1_1)<-FALSE
						l$Series_Matrix$Graph_GSEA_GO$BP<<-list()
						tr<<-gtree(offspring=tree,container=g1_1)
						size(tr)<-c(300,400)
						visible(g1_1)<-TRUE
					}
					display()	
				}
				if(length(which(x=="Online_Data"))!=0)
				{
					try(dispose(view_ww),silent=TRUE)
					GO.vec<-rownames(GOresultBP_O)[GOresultBP_O$Pvalue<=p_v]
					g<-GOGraph(GO.vec,GOBPPARENTS)
					g<-removeNode("all",g)
					nodes<-buildNodeList(g)
					focusnode<-sapply(nodes,name) %in% GO.vec
					names(focusnode)<-names(nodes)
					nodefill<-ifelse(focusnode,"yellow","white")
					nodefill_gsea_goBP_O<<-nodefill
					g_gsea_goBP_O<<-g
					nAttrs<-list()
					nAttrs$fillcolor<-nodefill
					graph_gsea_goBP_O<<-plot(g,nodeAttrs=nAttrs)
					terms<-getGOTerm(nodes(g))
					legend<-data.frame(terms)
					legend_gsea_goBP_O<<-data.frame(rownames(legend),legend)
					colnames(legend_gsea_goBP_O)<<-c("Identifier","BP")
					view_ww<<-gwindow("Graph_Legend",visible=FALSE,height=400,width=600)
					gtable(legend_gsea_goBP_O,container=view_ww)
					visible(view_ww)<<-TRUE
					if(length(graph_gsea_goBP_O)!=0){
						visible(g1_1)<-FALSE
						l$Online_Data$Graph_GSEA_GO$BP<<-list()
						tr<<-gtree(offspring=tree,container=g1_1)
						size(tr)<-c(300,400)
						visible(g1_1)<-TRUE
					}
					display()	
				}
				svalue(sb)<-"Done"
				dispose(w_dge)
				}else{
				gmessage("Plz select the data for generating Co-expression network","Select Data")
			}
		},container=gp2_dge,anchor=c(1,-1)
		)
		visible(w_dge)<-TRUE
	},container=gp_gsea2,anchor=c(1,-1)
	)
}
