graph_gsta_goCC<-function(h,...){
	try(({GOtable.outCC_Affy<-GOtable.outCC_Affy;GOtable.outCC_Ag1<-GOtable.outCC_Ag1;GOtable.outCC_Ag2<-GOtable.outCC_Ag2;
		GOtable.outCC_Il_B<-GOtable.outCC_Il_B;GOtable.outCC_Il_L<-GOtable.outCC_Il_L;GOtable.outCC_N<-GOtable.outCC_N;
		GOtable.outCC_S<-GOtable.outCC_S;GOtable.outCC_O<-GOtable.outCC_O;g1_1<-g1_1;l<-l;tree<-tree;
	}),silent=TRUE)
	platforms=NULL;
	aa=0;bb=0;cc=0;dd=0;ee=0;ff=0;gg=0;hh=0;
	try(({
		if(exists("GOtable.outCC_Affy"))aa=length(GOtable.outCC_Affy)
		if(exists("GOtable.outCC_Ag1"))bb=length(GOtable.outCC_Ag1)
		if(exists("GOtable.outCC_Ag2"))cc=length(GOtable.outCC_Ag2)
		if(exists("GOtable.outCC_Il_B"))dd=length(GOtable.outCC_Il_B)
		if(exists("GOtable.outCC_Il_L"))ee=length(GOtable.outCC_Il_L)
		if(exists("GOtable.outCC_N"))ff=length(GOtable.outCC_N)
		if(exists("GOtable.outCC_S"))gg=length(GOtable.outCC_S)
		if(exists("GOtable.outCC_O"))hh=length(GOtable.outCC_O)
		}),silent=TRUE)
	if(aa!=0)platforms=c(platforms,"Affymetrix")
	if(bb!=0)platforms=c(platforms,"Agilent_OneColor")
	if(cc!=0)platforms=c(platforms,"Agilent_TwoColor")
	if(dd!=0)platforms=c(platforms,"Illumina_Beadarray")
	if(ee!=0)platforms=c(platforms,"Illumina_Lumi")
	if(ff!=0)platforms=c(platforms,"Nimblegen")
	if(gg!=0)platforms=c(platforms,"Series_Matrix")
	if(hh!=0)platforms=c(platforms,"Online_Data")

	graph_gsta_goCC_Affy=NULL;graph_gsta_goCC_Ag1=NULL;graph_gsta_goCC_Ag2=NULL;graph_gsta_goCC_Il_B=NULL;graph_gsta_goCC_Il_L=NULL;
	graph_gsta_goCC_N=NULL;graph_gsta_goCC_S=NULL;graph_gsta_goCC_O=NULL;
	legend_gsta_goCC_Affy=NULL;legend_gsta_goCC_Ag1=NULL;legend_gsta_goCC_Ag2=NULL;legend_gsta_goCC_Il_B=NULL;legend_gsta_goCC_Il_L=NULL;
	legend_gsta_goCC_N=NULL;legend_gsta_goCC_S=NULL;legend_gsta_goCC_O=NULL;p_v=NULL;view_ww=NULL;
	nodefill_gsta_goCC_Affy=NULL;g_gsta_goCC_Affy=NULL;nodefill_gsta_goCC_Ag1=NULL;g_gsta_goCC_Ag1=NULL;
	nodefill_gsta_goCC_Ag2=NULL;g_gsta_goCC_Ag2=NULL;nodefill_gsta_goCC_Il_B=NULL;g_gsta_goCC_Il_B=NULL;
	nodefill_gsta_goCC_Il_L=NULL;g_gsta_goCC_Il_L=NULL;nodefill_gsta_goCC_N=NULL;g_gsta_goCC_N=NULL;
	nodefill_gsta_goCC_S=NULL;g_gsta_goCC_S=NULL;nodefill_gsta_goCC_O=NULL;g_gsta_goCC_O=NULL;

	rm(graph_gsta_goCC_Affy,graph_gsta_goCC_Ag1,graph_gsta_goCC_Ag2,graph_gsta_goCC_Il_B,graph_gsta_goCC_Il_L,
	graph_gsta_goCC_N,graph_gsta_goCC_S,graph_gsta_goCC_O,
	nodefill_gsta_goCC_Affy,g_gsta_goCC_Affy,nodefill_gsta_goCC_Ag1,g_gsta_goCC_Ag1,
	nodefill_gsta_goCC_Ag2,g_gsta_goCC_Ag2,nodefill_gsta_goCC_Il_B,g_gsta_goCC_Il_B,
	nodefill_gsta_goCC_Il_L,g_gsta_goCC_Il_L,nodefill_gsta_goCC_N,g_gsta_goCC_N,
	nodefill_gsta_goCC_S,g_gsta_goCC_S,nodefill_gsta_goCC_O,g_gsta_goCC_O,
	legend_gsta_goCC_Affy,legend_gsta_goCC_Ag1,legend_gsta_goCC_Ag2,legend_gsta_goCC_Il_B,legend_gsta_goCC_Il_L,
	legend_gsta_goCC_N,legend_gsta_goCC_S,legend_gsta_goCC_O,p_v,view_ww)

	x=NULL
	f<-function(h,...){
		x<<-svalue(h$obj)
		}
	z=NULL
	p_value=c(0.0000001,0.000001,0.00001,0.0001,0.001,0.01,0.05,0.1,0.5,1)
	w_gsea<-gwindow("Select p-value",horizontal=FALSE,height=100,width=100)
	gp_gsea<-ggroup(container=w_gsea,horizontal=FALSE)
	glabel("p-value",container=gp_gsea)
	cb_gsea<-gcombobox(p_value,editable=TRUE,selected=7,container=gp_gsea,handler=function(h,...){
		z<-svalue(h$obj)
		p_v<<-as.numeric(z)
	}
	)

	gp_gsea2<-ggroup(container=w_gsea)
	gbutton("CANCEL",border=TRUE,handler=function(h,...){
		p_v<<-0.05
		svalue(sb)<-"Done"
		dispose(w_gsea)
	},container=gp_gsea2,anchor=c(1,-1))
	gbutton("OK",border=TRUE,handler=function(h,...){
		z<-svalue(cb_gsea)
		p_v<<-as.numeric(z)
		dispose(w_gsea)
		svalue(sb)<-"				Please wait while Graphs.."
		w_dge<-gwindow("Select your data",width=260,height=280,visible=FALSE,horizontal=FALSE)
		gp_dge<-ggroup(container=w_dge,horizontal=FALSE)
		cbg_dge<-gcheckboxgroup(platforms,container=gp_dge,handler=f)
		svalue(cbg_dge,index=FALSE)<-1:8
		gp2_dge<-ggroup(container=gp_dge,width=30,height=15,horizontal=TRUE)
		addSpring(gp2_dge)
		y<-gbutton("CANCEL",border=TRUE,handler=function(h,...){
			dispose(w_dge)
		},container=gp2_dge,anchor=c(1,-1))
		y2<-gbutton("OK",border=TRUE,handler=function(h,...){
			if(length(x)!=0){
				dispose(w_dge)
				if(length(which(x=="Affymetrix"))!=0)
				{
					try(dispose(view_ww),silent=TRUE)
					GO.vec<-rownames(GOtable.outCC_Affy)[GOtable.outCC_Affy$"p-value"<=p_v]
					g<-GOGraph(GO.vec,GOCCPARENTS)
					g<-removeNode("all",g)
					nodes<-buildNodeList(g)
					focusnode<-sapply(nodes,name) %in% GO.vec
					names(focusnode)<-names(nodes)
					nodefill<-ifelse(focusnode,"yellow","white")
					nodefill_gsta_goCC_Affy<<-nodefill
					g_gsta_goCC_Affy<<-g
					nAttrs<-list()
					nAttrs$fillcolor<-nodefill
					graph_gsta_goCC_Affy<<-plot(g,nodeAttrs=nAttrs)
					terms<-getGOTerm(nodes(g))
					legend<-data.frame(terms)
					legend_gsta_goCC_Affy<<-data.frame(rownames(legend),legend)
					colnames(legend_gsta_goCC_Affy)<<-c("Identifier","CC")
					view_ww<<-gwindow("Graph_Legend",visible=FALSE,height=400,width=600)
					gtable(legend_gsta_goCC_Affy,container=view_ww)
					visible(view_ww)<<-TRUE
					if(length(graph_gsta_goCC_Affy)!=0){
						visible(g1_1)<-FALSE
						l$Affymetrix$Graph_GSTA_GO$CC<<-list()
						tr<<-gtree(offspring=tree,container=g1_1)
						size(tr)<-c(300,400)
						visible(g1_1)<-TRUE
					}
					display()	
				}
				if(length(which(x=="Agilent_OneColor"))!=0)
				{
					try(dispose(view_ww),silent=TRUE)
					GO.vec<-rownames(GOtable.outCC_Ag1)[GOtable.outCC_Ag1$"p-value"<=p_v]
					g<-GOGraph(GO.vec,GOCCPARENTS)
					g<-removeNode("all",g)
					nodes<-buildNodeList(g)
					focusnode<-sapply(nodes,name) %in% GO.vec
					names(focusnode)<-names(nodes)
					nodefill<-ifelse(focusnode,"yellow","white")
					nodefill_gsta_goCC_Ag1<<-nodefill
					g_gsta_goCC_Ag1<<-g
					nAttrs<-list()
					nAttrs$fillcolor<-nodefill
					graph_gsta_goCC_Ag1<<-plot(g,nodeAttrs=nAttrs)
					terms<-getGOTerm(nodes(g))
					legend<-data.frame(terms)
					legend_gsta_goCC_Ag1<<-data.frame(rownames(legend),legend)
					colnames(legend_gsta_goCC_Ag1)<<-c("Identifier","CC")
					view_ww<<-gwindow("Graph_Legend",visible=FALSE,height=400,width=600)
					gtable(legend_gsta_goCC_Ag1,container=view_ww)
					visible(view_ww)<<-TRUE
					if(length(graph_gsta_goCC_Ag1)!=0){
						visible(g1_1)<-FALSE
						l$Agilent_OneColor$Graph_GSTA_GO$CC<<-list()
						tr<<-gtree(offspring=tree,container=g1_1)
						size(tr)<-c(300,400)
						visible(g1_1)<-TRUE
					}
					display()	
				}
				if(length(which(x=="Agilent_TwoColor"))!=0)
				{
					try(dispose(view_ww),silent=TRUE)
					GO.vec<-rownames(GOtable.outCC_Ag2)[GOtable.outCC_Ag2$"p-value"<=p_v]
					g<-GOGraph(GO.vec,GOCCPARENTS)
					g<-removeNode("all",g)
					nodes<-buildNodeList(g)
					focusnode<-sapply(nodes,name) %in% GO.vec
					names(focusnode)<-names(nodes)
					nodefill<-ifelse(focusnode,"yellow","white")
					nodefill_gsta_goCC_Ag2<<-nodefill
					g_gsta_goCC_Ag2<<-g
					nAttrs<-list()
					nAttrs$fillcolor<-nodefill
					graph_gsta_goCC_Ag2<<-plot(g,nodeAttrs=nAttrs)
					terms<-getGOTerm(nodes(g))
					legend<-data.frame(terms)
					legend_gsta_goCC_Ag2<<-data.frame(rownames(legend),legend)
					colnames(legend_gsta_goCC_Ag2)<<-c("Identifier","CC")
					view_ww<<-gwindow("Graph_Legend",visible=FALSE,height=400,width=600)
					gtable(legend_gsta_goCC_Ag2,container=view_ww)
					visible(view_ww)<<-TRUE
					if(length(graph_gsta_goCC_Ag2)!=0){
						visible(g1_1)<-FALSE
						l$Agilent_TwoColor$Graph_GSTA_GO$CC<<-list()
						tr<<-gtree(offspring=tree,container=g1_1)
						size(tr)<-c(300,400)
						visible(g1_1)<-TRUE
					}
					display()	
				}
				if(length(which(x=="Illumina_Beadarray"))!=0)
				{
					try(dispose(view_ww),silent=TRUE)
					GO.vec<-rownames(GOtable.outCC_Il_B)[GOtable.outCC_Il_B$"p-value"<=p_v]
					g<-GOGraph(GO.vec,GOCCPARENTS)
					g<-removeNode("all",g)
					nodes<-buildNodeList(g)
					focusnode<-sapply(nodes,name) %in% GO.vec
					names(focusnode)<-names(nodes)
					nodefill<-ifelse(focusnode,"yellow","white")
					nodefill_gsta_goCC_Il_B<<-nodefill
					g_gsta_goCC_Il_B<<-g
					nAttrs<-list()
					nAttrs$fillcolor<-nodefill
					graph_gsta_goCC_Il_B<<-plot(g,nodeAttrs=nAttrs)
					terms<-getGOTerm(nodes(g))
					legend<-data.frame(terms)
					legend_gsta_goCC_Il_B<<-data.frame(rownames(legend),legend)
					colnames(legend_gsta_goCC_Il_B)<<-c("Identifier","CC")
					view_ww<<-gwindow("Graph_Legend",visible=FALSE,height=400,width=600)
					gtable(legend_gsta_goCC_Il_B,container=view_ww)
					visible(view_ww)<<-TRUE
					if(length(graph_gsta_goCC_Il_B)!=0){
						visible(g1_1)<-FALSE
						l$Illumina_Beadarray$Graph_GSTA_GO$CC<<-list()
						tr<<-gtree(offspring=tree,container=g1_1)
						size(tr)<-c(300,400)
						visible(g1_1)<-TRUE
					}
					display()	
				}
				if(length(which(x=="Illumina_Lumi"))!=0)
				{
					try(dispose(view_ww),silent=TRUE)
					GO.vec<-rownames(GOtable.outCC_Il_L)[GOtable.outCC_Il_L$"p-value"<=p_v]
					g<-GOGraph(GO.vec,GOCCPARENTS)
					g<-removeNode("all",g)
					nodes<-buildNodeList(g)
					focusnode<-sapply(nodes,name) %in% GO.vec
					names(focusnode)<-names(nodes)
					nodefill<-ifelse(focusnode,"yellow","white")
					nodefill_gsta_goCC_Il_L<<-nodefill
					g_gsta_goCC_Il_L<<-g
					nAttrs<-list()
					nAttrs$fillcolor<-nodefill
					graph_gsta_goCC_Il_L<<-plot(g,nodeAttrs=nAttrs)
					terms<-getGOTerm(nodes(g))
					legend<-data.frame(terms)
					legend_gsta_goCC_Il_L<<-data.frame(rownames(legend),legend)
					colnames(legend_gsta_goCC_Il_L)<<-c("Identifier","CC")
					view_ww<<-gwindow("Graph_Legend",visible=FALSE,height=400,width=600)
					gtable(legend_gsta_goCC_Il_L,container=view_ww)
					visible(view_ww)<<-TRUE
					if(length(graph_gsta_goCC_Il_L)!=0){
						visible(g1_1)<-FALSE
						l$Illumina_Lumi$Graph_GSTA_GO$CC<<-list()
						tr<<-gtree(offspring=tree,container=g1_1)
						size(tr)<-c(300,400)
						visible(g1_1)<-TRUE
					}
					display()	
				}
				if(length(which(x=="Nimblegen"))!=0)
				{
					try(dispose(view_ww),silent=TRUE)
					GO.vec<-rownames(GOtable.outCC_N)[GOtable.outCC_N$"p-value"<=p_v]
					g<-GOGraph(GO.vec,GOCCPARENTS)
					g<-removeNode("all",g)
					nodes<-buildNodeList(g)
					focusnode<-sapply(nodes,name) %in% GO.vec
					names(focusnode)<-names(nodes)
					nodefill<-ifelse(focusnode,"yellow","white")
					nodefill_gsta_goCC_N<<-nodefill
					g_gsta_goCC_N<<-g
					nAttrs<-list()
					nAttrs$fillcolor<-nodefill
					graph_gsta_goCC_N<<-plot(g,nodeAttrs=nAttrs)
					terms<-getGOTerm(nodes(g))
					legend<-data.frame(terms)
					legend_gsta_goCC_N<<-data.frame(rownames(legend),legend)
					colnames(legend_gsta_goCC_N)<<-c("Identifier","CC")
					view_ww<<-gwindow("Graph_Legend",visible=FALSE,height=400,width=600)
					gtable(legend_gsta_goCC_N,container=view_ww)
					visible(view_ww)<<-TRUE
					if(length(graph_gsta_goCC_N)!=0){
						visible(g1_1)<-FALSE
						l$Nimblegen$Graph_GSTA_GO$CC<<-list()
						tr<<-gtree(offspring=tree,container=g1_1)
						size(tr)<-c(300,400)
						visible(g1_1)<-TRUE
					}
					display()	
				}
				if(length(which(x=="Series_Matrix"))!=0)
				{
					try(dispose(view_ww),silent=TRUE)
					GO.vec<-rownames(GOtable.outCC_S)[GOtable.outCC_S$"p-value"<=p_v]
					g<-GOGraph(GO.vec,GOCCPARENTS)
					g<-removeNode("all",g)
					nodes<-buildNodeList(g)
					focusnode<-sapply(nodes,name) %in% GO.vec
					names(focusnode)<-names(nodes)
					nodefill<-ifelse(focusnode,"yellow","white")
					nodefill_gsta_goCC_S<<-nodefill
					g_gsta_goCC_S<<-g
					nAttrs<-list()
					nAttrs$fillcolor<-nodefill
					graph_gsta_goCC_S<<-plot(g,nodeAttrs=nAttrs)
					terms<-getGOTerm(nodes(g))
					legend<-data.frame(terms)
					legend_gsta_goCC_S<<-data.frame(rownames(legend),legend)
					colnames(legend_gsta_goCC_S)<<-c("Identifier","CC")
					view_ww<<-gwindow("Graph_Legend",visible=FALSE,height=400,width=600)
					gtable(legend_gsta_goCC_S,container=view_ww)
					visible(view_ww)<<-TRUE
					if(length(graph_gsta_goCC_S)!=0){
						visible(g1_1)<-FALSE
						l$Series_Matrix$Graph_GSTA_GO$CC<<-list()
						tr<<-gtree(offspring=tree,container=g1_1)
						size(tr)<-c(300,400)
						visible(g1_1)<-TRUE
					}
					display()	
				}
				if(length(which(x=="Online_Data"))!=0)
				{
					try(dispose(view_ww),silent=TRUE)
					GO.vec<-rownames(GOtable.outCC_O)[GOtable.outCC_O$"p-value"<=p_v]
					g<-GOGraph(GO.vec,GOCCPARENTS)
					g<-removeNode("all",g)
					nodes<-buildNodeList(g)
					focusnode<-sapply(nodes,name) %in% GO.vec
					names(focusnode)<-names(nodes)
					nodefill<-ifelse(focusnode,"yellow","white")
					nodefill_gsta_goCC_O<<-nodefill
					g_gsta_goCC_O<<-g
					nAttrs<-list()
					nAttrs$fillcolor<-nodefill
					graph_gsta_goCC_O<<-plot(g,nodeAttrs=nAttrs)
					terms<-getGOTerm(nodes(g))
					legend<-data.frame(terms)
					legend_gsta_goCC_O<<-data.frame(rownames(legend),legend)
					colnames(legend_gsta_goCC_O)<<-c("Identifier","CC")
					view_ww<<-gwindow("Graph_Legend",visible=FALSE,height=400,width=600)
					gtable(legend_gsta_goCC_O,container=view_ww)
					visible(view_ww)<<-TRUE
					if(length(graph_gsta_goCC_O)!=0){
						visible(g1_1)<-FALSE
						l$Online_Data$Graph_GSTA_GO$CC<<-list()
						tr<<-gtree(offspring=tree,container=g1_1)
						size(tr)<-c(300,400)
						visible(g1_1)<-TRUE
					}
					display()	
				}
				svalue(sb)<-"Done"
				dispose(w_dge)
				}else{
				gmessage("Plz select the data for generating Co-expression network","Select Data")
			}
		},container=gp2_dge,anchor=c(1,-1)
		)
		visible(w_dge)<-TRUE
	},container=gp_gsea2,anchor=c(1,-1)
	)
}
