maGUI<-function(...){
	ma_w=NULL;ma_frame1=NULL;ma_frame2=NULL;treeview=NULL;
	rm(ma_w,ma_frame1,ma_frame2,treeview)
	ma_w<<-tktoplevel(height=500,width=1000)
	tkwm.title(ma_w,"maGUI")
	tkwm.resizable(ma_w,0,0)
	ma_frame1<<-ttkframe(ma_w,height=500,width=300)
	treeview<<-ttktreeview(ma_frame1,columns=1,show="headings",height=24)
	scrX1<-ttkscrollbar(ma_frame1,orient="horizont",command=function(...)tcl(treeview,'xview',...))
	scrY1<-ttkscrollbar(ma_frame1,orient="vertical",command=function(...)tcl(treeview,'yview',...))
	tkpack(scrX1,side="bottom",fill="x",expand=FALSE)	# x scrollbar
	tkpack(scrY1,side="right",fill="y",expand=FALSE,pady=c(0,18)) #y scrollbar
	tkpack(treeview,fill="both",expand=TRUE)
	tkpack(ma_frame1,expand=TRUE,fill="both",side="left")
	ma_frame2<<-ttkframe(ma_w,height=500,width=820)
	tkpack.propagate(ma_frame2,FALSE)
	tkpack(ma_frame2,expand=TRUE,fill="both",side="right")
	ma_menubar<-tkmenu(ma_w)
	tcl("option","add","*tearOff",0)
	tkconfigure(ma_w,menu=ma_menubar)
	ma_filemenu<-tkmenu(ma_menubar)
	
	taf_i=NULL;tag1_i=NULL;tag2_i=NULL;tilb_i=NULL;till_i=NULL;tnbl_i=NULL;tsmt_i=NULL;tonl_i=NULL;
	taf_i<<-0;tag1_i<<-0;tag2_i<<-0;tilb_i<<-0;till_i<<-0;tnbl_i<<-0;tsmt_i<<-0;tonl_i<<-0;
	
	ma_img=NULL;ma_img2=NULL;ma_export=NULL;ma_tab=NULL;ma_fig=NULL;
	tree_prnts=NULL;legend_tab=NULL;
	ma_img<<-NULL;ma_img2<<-NULL;ma_export<<-NULL;ma_tab<<-NULL;ma_fig<<-NULL;
	tree_prnts<<-NULL;legend_tab<<-NULL;
	
	folder_Affy=NULL;ann_Affy=NULL;l_datAffy=NULL;dat2Affy.m2=NULL;ta_affy_norm2=NULL;samp_Affy=NULL;
	fit2_Affy=NULL;dat2Affy.f3=NULL;ta_affy_filt2=NULL;dat2Affy.s3=NULL;ta_affy_stat2=NULL;
	pca_Affy=NULL;sample.clust_Affy=NULL;DE_AffyAll=NULL;DE_Affy_2=NULL;ta_affy_dge2=NULL;clas_Affy=NULL;
	GOresultBP_Affy=NULL;ta_affy_gsea_gobp=NULL;GOresultMF_Affy=NULL;ta_affy_gsea_gomf=NULL;
	GOresultCC_Affy=NULL;ta_affy_gsea_gocc=NULL;KEGGresult_Affy=NULL;ta_affy_gsea_kegg=NULL;
	GOtable.outBP_Affy=NULL;ta_affy_gsta_gobp=NULL;GOtable.outMF_Affy=NULL;ta_affy_gsta_gomf=NULL;
	GOtable.outCC_Affy=NULL;ta_affy_gsta_gocc=NULL;KEGGtable.out_Affy=NULL;ta_affy_gsta_kegg=NULL;
	graph_gsea_goBP_Affy=NULL;ta_affy_legend_gsea_gobp=NULL;graph_gsea_goMF_Affy=NULL;ta_affy_legend_gsea_gomf=NULL;
	graph_gsea_goCC_Affy=NULL;ta_affy_legend_gsea_gocc=NULL;graph_gsea_KEGG_Affy=NULL;ta_affy_legend_gsea_kegg=NULL;
	graph_gsta_goBP_Affy=NULL;ta_affy_legend_gsta_gobp=NULL;graph_gsta_goMF_Affy=NULL;ta_affy_legend_gsta_gomf=NULL;
	graph_gsta_goCC_Affy=NULL;ta_affy_legend_gsta_gocc=NULL;graph_gsta_KEGG_Affy=NULL;ta_affy_legend_gsta_kegg=NULL;
	legend_gsea_goBP_Affy=NULL;legend_gsea_goMF_Affy=NULL;legend_gsea_goCC_Affy=NULL;legend_gsea_KEGG_Affy=NULL;
	legend_gsta_goBP_Affy=NULL;legend_gsta_goMF_Affy=NULL;legend_gsta_goCC_Affy=NULL;legend_gsta_KEGG_Affy=NULL;
	nodefill_gsea_goBP_Affy=NULL;nodefill_gsea_goMF_Affy=NULL;nodefill_gsea_goCC_Affy=NULL;nodefill_gsea_KEGG_Affy=NULL;
	nodefill_gsta_goBP_Affy=NULL;nodefill_gsta_goMF_Affy=NULL;nodefill_gsta_goCC_Affy=NULL;nodefill_gsta_KEGG_Affy=NULL;
	genes_Affy=NULL;ta_affy_genes=NULL;myGraph_Affy=NULL;ssize_Affy=NULL;
	
	folder_Ag1=NULL;ann_Ag1=NULL;l_datAgOne=NULL;datAgOne2.m2=NULL;ta_ag1_norm2=NULL;samp_Ag1=NULL;
	fit2_Ag1=NULL;datAgOne2.f3=NULL;ta_ag1_filt2=NULL;datAgOne2.s3=NULL;ta_ag1_stat2=NULL;
	pca_Ag1=NULL;sample.clust_Ag1=NULL;DE_Ag1All=NULL;DE_Ag1_2=NULL;ta_ag1_dge2=NULL;clas_Ag1=NULL;
	GOresultBP_Ag1=NULL;ta_ag1_gsea_gobp=NULL;GOresultMF_Ag1=NULL;ta_ag1_gsea_gomf=NULL;
	GOresultCC_Ag1=NULL;ta_ag1_gsea_gocc=NULL;KEGGresult_Ag1=NULL;ta_ag1_gsea_kegg=NULL;
	GOtable.outBP_Ag1=NULL;ta_ag1_gsta_gobp=NULL;GOtable.outMF_Ag1=NULL;ta_ag1_gsta_gomf=NULL;
	GOtable.outCC_Ag1=NULL;ta_ag1_gsta_gocc=NULL;KEGGtable.out_Ag1=NULL;ta_ag1_gsta_kegg=NULL;
	graph_gsea_goBP_Ag1=NULL;ta_affy_legend_gsea_gobp=NULL;graph_gsea_goMF_Ag1=NULL;ta_affy_legend_gsea_gomf=NULL;
	graph_gsea_goCC_Ag1=NULL;ta_affy_legend_gsea_gocc=NULL;graph_gsea_KEGG_Ag1=NULL;ta_affy_legend_gsea_kegg=NULL;
	graph_gsta_goBP_Ag1=NULL;ta_affy_legend_gsta_gobp=NULL;graph_gsta_goMF_Ag1=NULL;ta_affy_legend_gsta_gomf=NULL;
	graph_gsta_goCC_Ag1=NULL;ta_affy_legend_gsta_gocc=NULL;graph_gsta_KEGG_Ag1=NULL;ta_affy_legend_gsta_kegg=NULL;
	legend_gsea_goBP_Ag1=NULL;legend_gsea_goMF_Ag1=NULL;legend_gsea_goCC_Ag1=NULL;legend_gsea_KEGG_Ag1=NULL;
	legend_gsta_goBP_Ag1=NULL;legend_gsta_goMF_Ag1=NULL;legend_gsta_goCC_Ag1=NULL;legend_gsta_KEGG_Ag1=NULL;
	nodefill_gsea_goBP_Ag1=NULL;nodefill_gsea_goMF_Ag1=NULL;nodefill_gsea_goCC_Ag1=NULL;nodefill_gsea_KEGG_Ag1=NULL;
	nodefill_gsta_goBP_Ag1=NULL;nodefill_gsta_goMF_Ag1=NULL;nodefill_gsta_goCC_Ag1=NULL;nodefill_gsta_KEGG_Ag1=NULL;
	genes_Ag1=NULL;ta_ag1_genes=NULL;myGraph_Ag1=NULL;ssize_Ag1=NULL;

	folder_Ag2=NULL;ann_Ag2=NULL;l_datAgTwo=NULL;datAgTwo2.m2=NULL;ta_ag2_norm2=NULL;samp_Ag2=NULL;
	fit2_Ag2=NULL;datAgTwo2.f3=NULL;ta_ag2_filt2=NULL;datAgTwo2.s3=NULL;ta_ag2_stat2=NULL;
	pca_Ag2=NULL;sample.clust_Ag2=NULL;DE_Ag2All=NULL;DE_Ag2_2=NULL;ta_ag2_dge2=NULL;clas_Ag2=NULL;
	GOresultBP_Ag2=NULL;ta_ag2_gsea_gobp=NULL;GOresultMF_Ag2=NULL;ta_ag2_gsea_gomf=NULL;
	GOresultCC_Ag2=NULL;ta_ag2_gsea_gocc=NULL;KEGGresult_Ag2=NULL;ta_ag2_gsea_kegg=NULL;
	GOtable.outBP_Ag2=NULL;ta_ag2_gsta_gobp=NULL;GOtable.outMF_Ag2=NULL;ta_ag2_gsta_gomf=NULL;
	GOtable.outCC_Ag2=NULL;ta_ag2_gsta_gocc=NULL;KEGGtable.out_Ag2=NULL;ta_ag2_gsta_kegg=NULL;
	graph_gsea_goBP_Ag2=NULL;ta_affy_legend_gsea_gobp=NULL;graph_gsea_goMF_Ag2=NULL;ta_affy_legend_gsea_gomf=NULL;
	graph_gsea_goCC_Ag2=NULL;ta_affy_legend_gsea_gocc=NULL;graph_gsea_KEGG_Ag2=NULL;ta_affy_legend_gsea_kegg=NULL;
	graph_gsta_goBP_Ag2=NULL;ta_affy_legend_gsta_gobp=NULL;graph_gsta_goMF_Ag2=NULL;ta_affy_legend_gsta_gomf=NULL;
	graph_gsta_goCC_Ag2=NULL;ta_affy_legend_gsta_gocc=NULL;graph_gsta_KEGG_Ag2=NULL;ta_affy_legend_gsta_kegg=NULL;
	legend_gsea_goBP_Ag2=NULL;legend_gsea_goMF_Ag2=NULL;legend_gsea_goCC_Ag2=NULL;legend_gsea_KEGG_Ag2=NULL;
	legend_gsta_goBP_Ag2=NULL;legend_gsta_goMF_Ag2=NULL;legend_gsta_goCC_Ag2=NULL;legend_gsta_KEGG_Ag2=NULL;
	nodefill_gsea_goBP_Ag2=NULL;nodefill_gsea_goMF_Ag2=NULL;nodefill_gsea_goCC_Ag2=NULL;nodefill_gsea_KEGG_Ag2=NULL;
	nodefill_gsta_goBP_Ag2=NULL;nodefill_gsta_goMF_Ag2=NULL;nodefill_gsta_goCC_Ag2=NULL;nodefill_gsta_KEGG_Ag2=NULL;
	genes_Ag2=NULL;ta_ag2_genes=NULL;myGraph_Ag2=NULL;ssize_Ag2=NULL;
	
	folder_Il_B=NULL;ann_Il_B=NULL;l_datIllBA=NULL;datIllBA2.m2=NULL;ta_ilb_norm2=NULL;samp_Il_B=NULL;
	fit2_Il_B=NULL;datIllBA2.f3=NULL;ta_ilb_filt2=NULL;datIllBA2.s3=NULL;ta_ilb_stat2=NULL;
	pca_Il_B=NULL;sample.clust_Il_B=NULL;DE_Il_BAll=NULL;DE_Il_B_2=NULL;ta_ilb_dge2=NULL;clas_Il_B=NULL;
	GOresultBP_Il_B=NULL;ta_ilb_gsea_gobp=NULL;GOresultMF_Il_B=NULL;ta_ilb_gsea_gomf=NULL;
	GOresultCC_Il_B=NULL;ta_ilb_gsea_gocc=NULL;KEGGresult_Il_B=NULL;ta_ilb_gsea_kegg=NULL;
	GOtable.outBP_Il_B=NULL;ta_ilb_gsta_gobp=NULL;GOtable.outMF_Il_B=NULL;ta_ilb_gsta_gomf=NULL;
	GOtable.outCC_Il_B=NULL;ta_ilb_gsta_gocc=NULL;KEGGtable.out_Il_B=NULL;ta_ilb_gsta_kegg=NULL;
	graph_gsea_goBP_Il_B=NULL;ta_affy_legend_gsea_gobp=NULL;graph_gsea_goMF_Il_B=NULL;ta_affy_legend_gsea_gomf=NULL;
	graph_gsea_goCC_Il_B=NULL;ta_affy_legend_gsea_gocc=NULL;graph_gsea_KEGG_Il_B=NULL;ta_affy_legend_gsea_kegg=NULL;
	graph_gsta_goBP_Il_B=NULL;ta_affy_legend_gsta_gobp=NULL;graph_gsta_goMF_Il_B=NULL;ta_affy_legend_gsta_gomf=NULL;
	graph_gsta_goCC_Il_B=NULL;ta_affy_legend_gsta_gocc=NULL;graph_gsta_KEGG_Il_B=NULL;ta_affy_legend_gsta_kegg=NULL;
	legend_gsea_goBP_Il_B=NULL;legend_gsea_goMF_Il_B=NULL;legend_gsea_goCC_Il_B=NULL;legend_gsea_KEGG_Il_B=NULL;
	legend_gsta_goBP_Il_B=NULL;legend_gsta_goMF_Il_B=NULL;legend_gsta_goCC_Il_B=NULL;legend_gsta_KEGG_Il_B=NULL;
	nodefill_gsea_goBP_Il_B=NULL;nodefill_gsea_goMF_Il_B=NULL;nodefill_gsea_goCC_Il_B=NULL;nodefill_gsea_KEGG_Il_B=NULL;
	nodefill_gsta_goBP_Il_B=NULL;nodefill_gsta_goMF_Il_B=NULL;nodefill_gsta_goCC_Il_B=NULL;nodefill_gsta_KEGG_Il_B=NULL;
	genes_Il_B=NULL;ta_ilb_genes=NULL;myGraph_Il_B=NULL;ssize_Il_B=NULL;
	
	folder_Il_L=NULL;ann_Il_L=NULL;l_lumi_data=NULL;lumi_NQ.m2=NULL;ta_ill_norm2=NULL;samp_Il_L=NULL;
	fit2_Il_L=NULL;lumi_NQ.f3=NULL;ta_ill_filt2=NULL;lumi_NQ.s3=NULL;ta_ill_stat2=NULL;
	pca_Il_L=NULL;sample.clust_Il_L=NULL;DE_Il_LAll=NULL;DE_Il_L_2=NULL;ta_ill_dge2=NULL;clas_Il_L=NULL;
	GOresultBP_Il_L=NULL;ta_ill_gsea_gobp=NULL;GOresultMF_Il_L=NULL;ta_ill_gsea_gomf=NULL;
	GOresultCC_Il_L=NULL;ta_ill_gsea_gocc=NULL;KEGGresult_Il_L=NULL;ta_ill_gsea_kegg=NULL;
	GOtable.outBP_Il_L=NULL;ta_ill_gsta_gobp=NULL;GOtable.outMF_Il_L=NULL;ta_ill_gsta_gomf=NULL;
	GOtable.outCC_Il_L=NULL;ta_ill_gsta_gocc=NULL;KEGGtable.out_Il_L=NULL;ta_ill_gsta_kegg=NULL;
	graph_gsea_goBP_Il_L=NULL;ta_affy_legend_gsea_gobp=NULL;graph_gsea_goMF_Il_L=NULL;ta_affy_legend_gsea_gomf=NULL;
	graph_gsea_goCC_Il_L=NULL;ta_affy_legend_gsea_gocc=NULL;graph_gsea_KEGG_Il_L=NULL;ta_affy_legend_gsea_kegg=NULL;
	graph_gsta_goBP_Il_L=NULL;ta_affy_legend_gsta_gobp=NULL;graph_gsta_goMF_Il_L=NULL;ta_affy_legend_gsta_gomf=NULL;
	graph_gsta_goCC_Il_L=NULL;ta_affy_legend_gsta_gocc=NULL;graph_gsta_KEGG_Il_L=NULL;ta_affy_legend_gsta_kegg=NULL;
	legend_gsea_goBP_Il_L=NULL;legend_gsea_goMF_Il_L=NULL;legend_gsea_goCC_Il_L=NULL;legend_gsea_KEGG_Il_L=NULL;
	legend_gsta_goBP_Il_L=NULL;legend_gsta_goMF_Il_L=NULL;legend_gsta_goCC_Il_L=NULL;legend_gsta_KEGG_Il_L=NULL;
	nodefill_gsea_goBP_Il_L=NULL;nodefill_gsea_goMF_Il_L=NULL;nodefill_gsea_goCC_Il_L=NULL;nodefill_gsea_KEGG_Il_L=NULL;
	nodefill_gsta_goBP_Il_L=NULL;nodefill_gsta_goMF_Il_L=NULL;nodefill_gsta_goCC_Il_L=NULL;nodefill_gsta_KEGG_Il_L=NULL;
	genes_Il_L=NULL;ta_ill_genes=NULL;myGraph_Il_L=NULL;ssize_Il_L=NULL;
	
	folder_N=NULL;ann_N=NULL;l_data.matrix_Nimblegen=NULL;data.matrix_Nimblegen2.m2=NULL;ta_nbl_norm2=NULL;samp_N=NULL;
	fit2_N=NULL;data.matrix_Nimblegen2.f3=NULL;ta_nbl_filt2=NULL;data.matrix_Nimblegen2.s3=NULL;ta_nbl_stat2=NULL;
	GOresultBP_N=NULL;ta_nbl_gsea_gobp=NULL;GOresultMF_N=NULL;ta_nbl_gsea_gomf=NULL;
	GOresultCC_N=NULL;ta_nbl_gsea_gocc=NULL;KEGGresult_N=NULL;ta_nbl_gsea_kegg=NULL;
	pca_N=NULL;sample.clust_N=NULL;DE_NAll=NULL;DE_N_2=NULL;ta_nbl_dge2=NULL;clas_N=NULL;
	GOtable.outBP_N=NULL;ta_nbl_gsta_gobp=NULL;GOtable.outMF_N=NULL;ta_nbl_gsta_gomf=NULL;
	GOtable.outCC_N=NULL;ta_nbl_gsta_gocc=NULL;KEGGtable.out_N=NULL;ta_nbl_gsta_kegg=NULL;
	graph_gsea_goBP_N=NULL;ta_affy_legend_gsea_gobp=NULL;graph_gsea_goMF_N=NULL;ta_affy_legend_gsea_gomf=NULL;
	graph_gsea_goCC_N=NULL;ta_affy_legend_gsea_gocc=NULL;graph_gsea_KEGG_N=NULL;ta_affy_legend_gsea_kegg=NULL;
	graph_gsta_goBP_N=NULL;ta_affy_legend_gsta_gobp=NULL;graph_gsta_goMF_N=NULL;ta_affy_legend_gsta_gomf=NULL;
	graph_gsta_goCC_N=NULL;ta_affy_legend_gsta_gocc=NULL;graph_gsta_KEGG_N=NULL;ta_affy_legend_gsta_kegg=NULL;
	legend_gsea_goBP_N=NULL;legend_gsea_goMF_N=NULL;legend_gsea_goCC_N=NULL;legend_gsea_KEGG_N=NULL;
	legend_gsta_goBP_N=NULL;legend_gsta_goMF_N=NULL;legend_gsta_goCC_N=NULL;legend_gsta_KEGG_N=NULL;
	nodefill_gsea_goBP_N=NULL;nodefill_gsea_goMF_N=NULL;nodefill_gsea_goCC_N=NULL;nodefill_gsea_KEGG_N=NULL;
	nodefill_gsta_goBP_N=NULL;nodefill_gsta_goMF_N=NULL;nodefill_gsta_goCC_N=NULL;nodefill_gsta_KEGG_N=NULL;
	genes_N=NULL;ta_nbl_genes=NULL;myGraph_N=NULL;ssize_N=NULL;
	
	folder_S=NULL;ann_S=NULL;l_data.matrix_series=NULL;l_data.matrixLog=NULL;l_data.matrixImp=NULL;data.matrixNorm.m2=NULL;ta_smt_norm2=NULL;
	samp_S=NULL;fit2_S=NULL;data.matrixNorm.f3=NULL;ta_smt_filt2=NULL;data.matrixNorm.s3=NULL;ta_smt_stat2=NULL;
	pca_S=NULL;sample.clust_S=NULL;DE_SAll=NULL;DE_S_2=NULL;ta_smt_dge2=NULL;clas_S=NULL;
	GOresultBP_S=NULL;ta_smt_gsea_gobp=NULL;GOresultMF_S=NULL;ta_smt_gsea_gomf=NULL;
	GOresultCC_S=NULL;ta_smt_gsea_gocc=NULL;KEGGresult_S=NULL;ta_smt_gsea_kegg=NULL;
	GOtable.outBP_S=NULL;ta_smt_gsta_gobp=NULL;GOtable.outMF_S=NULL;ta_smt_gsta_gomf=NULL;
	GOtable.outCC_S=NULL;ta_smt_gsta_gocc=NULL;KEGGtable.out_S=NULL;ta_smt_gsta_kegg=NULL;
	graph_gsea_goBP_S=NULL;ta_affy_legend_gsea_gobp=NULL;graph_gsea_goMF_S=NULL;ta_affy_legend_gsea_gomf=NULL;
	graph_gsea_goCC_S=NULL;ta_affy_legend_gsea_gocc=NULL;graph_gsea_KEGG_S=NULL;ta_affy_legend_gsea_kegg=NULL;
	graph_gsta_goBP_S=NULL;ta_affy_legend_gsta_gobp=NULL;graph_gsta_goMF_S=NULL;ta_affy_legend_gsta_gomf=NULL;
	graph_gsta_goCC_S=NULL;ta_affy_legend_gsta_gocc=NULL;graph_gsta_KEGG_S=NULL;ta_affy_legend_gsta_kegg=NULL;
	legend_gsea_goBP_S=NULL;legend_gsea_goMF_S=NULL;legend_gsea_goCC_S=NULL;legend_gsea_KEGG_S=NULL;
	legend_gsta_goBP_S=NULL;legend_gsta_goMF_S=NULL;legend_gsta_goCC_S=NULL;legend_gsta_KEGG_S=NULL;
	nodefill_gsea_goBP_S=NULL;nodefill_gsea_goMF_S=NULL;nodefill_gsea_goCC_S=NULL;nodefill_gsea_KEGG_S=NULL;
	nodefill_gsta_goBP_S=NULL;nodefill_gsta_goMF_S=NULL;nodefill_gsta_goCC_S=NULL;nodefill_gsta_KEGG_S=NULL;
	genes_S=NULL;ta_smt_genes=NULL;myGraph_S=NULL;ssize_S=NULL;
	
	folder_O=NULL;ann_O=NULL;l_data.matrix_online=NULL;l_data.matrix_onlineLog=NULL;l_data.matrix_onlineImp=NULL;data.matrix_onlineNorm.m2=NULL;
	ta_onl_norm2=NULL;samp_O=NULL;fit2_O=NULL;data.matrix_onlineNorm.f3=NULL;ta_onl_filt2=NULL;data.matrix_onlineNorm.s3=NULL;ta_onl_stat2=NULL;
	pca_O=NULL;sample.clust_O=NULL;DE_OAll=NULL;DE_O_2=NULL;ta_onl_dge2=NULL;clas_O=NULL;
	GOresultBP_O=NULL;ta_onl_gsea_gobp=NULL;GOresultMF_O=NULL;ta_onl_gsea_gomf=NULL;
	GOresultCC_O=NULL;ta_onl_gsea_gocc=NULL;KEGGresult_O=NULL;ta_onl_gsea_kegg=NULL;
	GOtable.outBP_O=NULL;ta_onl_gsta_gobp=NULL;GOtable.outMF_O=NULL;ta_onl_gsta_gomf=NULL;
	GOtable.outCC_O=NULL;ta_onl_gsta_gocc=NULL;KEGGtable.out_O=NULL;ta_onl_gsta_kegg=NULL;
	graph_gsea_goBP_O=NULL;ta_affy_legend_gsea_gobp=NULL;graph_gsea_goMF_O=NULL;ta_affy_legend_gsea_gomf=NULL;
	graph_gsea_goCC_O=NULL;ta_affy_legend_gsea_gocc=NULL;graph_gsea_KEGG_O=NULL;ta_affy_legend_gsea_kegg=NULL;
	graph_gsta_goBP_O=NULL;ta_affy_legend_gsta_gobp=NULL;graph_gsta_goMF_O=NULL;ta_affy_legend_gsta_gomf=NULL;
	graph_gsta_goCC_O=NULL;ta_affy_legend_gsta_gocc=NULL;graph_gsta_KEGG_O=NULL;ta_affy_legend_gsta_kegg=NULL;
	legend_gsea_goBP_O=NULL;legend_gsea_goMF_O=NULL;legend_gsea_goCC_O=NULL;legend_gsea_KEGG_O=NULL;
	legend_gsta_goBP_O=NULL;legend_gsta_goMF_O=NULL;legend_gsta_goCC_O=NULL;legend_gsta_KEGG_O=NULL;
	nodefill_gsea_goBP_O=NULL;nodefill_gsea_goMF_O=NULL;nodefill_gsea_goCC_O=NULL;nodefill_gsea_KEGG_O=NULL;
	nodefill_gsta_goBP_O=NULL;nodefill_gsta_goMF_O=NULL;nodefill_gsta_goCC_O=NULL;nodefill_gsta_KEGG_O=NULL;
	genes_O=NULL;ta_onl_genes=NULL;myGraph_O=NULL;ssize_O=NULL;

	folder_Affy<<-NULL;ann_Affy<<-NULL;l_datAffy<<-NULL;dat2Affy.m2<<-NULL;ta_affy_norm2<<-NULL;samp_Affy<<-NULL;
	fit2_Affy<<-NULL;dat2Affy.f3<<-NULL;ta_affy_filt2<<-NULL;dat2Affy.s3<<-NULL;ta_affy_stat2<<-NULL;
	pca_Affy<<-NULL;sample.clust_Affy<<-NULL;DE_AffyAll<<-NULL;DE_Affy_2<<-NULL;ta_affy_dge2<<-NULL;clas_Affy<<-NULL;
	GOresultBP_Affy<<-NULL;ta_affy_gsea_gobp<<-NULL;GOresultMF_Affy<<-NULL;ta_affy_gsea_gomf<<-NULL;
	GOresultCC_Affy<<-NULL;ta_affy_gsea_gocc<<-NULL;KEGGresult_Affy<<-NULL;ta_affy_gsea_kegg<<-NULL;
	GOtable.outBP_Affy<<-NULL;ta_affy_gsta_gobp<<-NULL;GOtable.outMF_Affy<<-NULL;ta_affy_gsta_gomf<<-NULL;
	GOtable.outCC_Affy<<-NULL;ta_affy_gsta_gocc<<-NULL;KEGGtable.out_Affy<<-NULL;ta_affy_gsta_kegg<<-NULL;
	graph_gsea_goBP_Affy<<-NULL;ta_affy_legend_gsea_gobp<<-NULL;graph_gsea_goMF_Affy<<-NULL;ta_affy_legend_gsea_gomf<<-NULL;
	graph_gsea_goCC_Affy<<-NULL;ta_affy_legend_gsea_gocc<<-NULL;graph_gsea_KEGG_Affy<<-NULL;ta_affy_legend_gsea_kegg<<-NULL;
	graph_gsta_goBP_Affy<<-NULL;ta_affy_legend_gsta_gobp<<-NULL;graph_gsta_goMF_Affy<<-NULL;ta_affy_legend_gsta_gomf<<-NULL;
	graph_gsta_goCC_Affy<<-NULL;ta_affy_legend_gsta_gocc<<-NULL;graph_gsta_KEGG_Affy<<-NULL;ta_affy_legend_gsta_kegg<<-NULL;
	legend_gsea_goBP_Affy<<-NULL;legend_gsea_goMF_Affy<<-NULL;legend_gsea_goCC_Affy<<-NULL;legend_gsea_KEGG_Affy<<-NULL;
	legend_gsta_goBP_Affy<<-NULL;legend_gsta_goMF_Affy<<-NULL;legend_gsta_goCC_Affy<<-NULL;legend_gsta_KEGG_Affy<<-NULL;
	nodefill_gsea_goBP_Affy<<-NULL;nodefill_gsea_goMF_Affy<<-NULL;nodefill_gsea_goCC_Affy<<-NULL;nodefill_gsea_KEGG_Affy<<-NULL;
	nodefill_gsta_goBP_Affy<<-NULL;nodefill_gsta_goMF_Affy<<-NULL;nodefill_gsta_goCC_Affy<<-NULL;nodefill_gsta_KEGG_Affy<<-NULL;
	genes_Affy<<-NULL;ta_affy_genes<<-NULL;myGraph_Affy<<-NULL;ssize_Affy<<-NULL;
	
	folder_Ag1<<-NULL;ann_Ag1<<-NULL;l_datAgOne<<-NULL;datAgOne2.m2<<-NULL;ta_ag1_norm2<<-NULL;samp_Ag1<<-NULL;
	fit2_Ag1<<-NULL;datAgOne2.f3<<-NULL;ta_ag1_filt2<<-NULL;datAgOne2.s3<<-NULL;ta_ag1_stat2<<-NULL;
	pca_Ag1<<-NULL;sample.clust_Ag1<<-NULL;DE_Ag1All<<-NULL;DE_Ag1_2<<-NULL;ta_ag1_dge2<<-NULL;clas_Ag1<<-NULL;
	GOresultBP_Ag1<<-NULL;ta_ag1_gsea_gobp<<-NULL;GOresultMF_Ag1<<-NULL;ta_ag1_gsea_gomf<<-NULL;
	GOresultCC_Ag1<<-NULL;ta_ag1_gsea_gocc<<-NULL;KEGGresult_Ag1<<-NULL;ta_ag1_gsea_kegg<<-NULL;
	GOtable.outBP_Ag1<<-NULL;ta_ag1_gsta_gobp<<-NULL;GOtable.outMF_Ag1<<-NULL;ta_ag1_gsta_gomf<<-NULL;
	GOtable.outCC_Ag1<<-NULL;ta_ag1_gsta_gocc<<-NULL;KEGGtable.out_Ag1<<-NULL;ta_ag1_gsta_kegg<<-NULL;
	graph_gsea_goBP_Ag1<<-NULL;ta_affy_legend_gsea_gobp<<-NULL;graph_gsea_goMF_Ag1<<-NULL;ta_affy_legend_gsea_gomf<<-NULL;
	graph_gsea_goCC_Ag1<<-NULL;ta_affy_legend_gsea_gocc<<-NULL;graph_gsea_KEGG_Ag1<<-NULL;ta_affy_legend_gsea_kegg<<-NULL;
	graph_gsta_goBP_Ag1<<-NULL;ta_affy_legend_gsta_gobp<<-NULL;graph_gsta_goMF_Ag1<<-NULL;ta_affy_legend_gsta_gomf<<-NULL;
	graph_gsta_goCC_Ag1<<-NULL;ta_affy_legend_gsta_gocc<<-NULL;graph_gsta_KEGG_Ag1<<-NULL;ta_affy_legend_gsta_kegg<<-NULL;
	legend_gsea_goBP_Ag1<<-NULL;legend_gsea_goMF_Ag1<<-NULL;legend_gsea_goCC_Ag1<<-NULL;legend_gsea_KEGG_Ag1<<-NULL;
	legend_gsta_goBP_Ag1<<-NULL;legend_gsta_goMF_Ag1<<-NULL;legend_gsta_goCC_Ag1<<-NULL;legend_gsta_KEGG_Ag1<<-NULL;
	nodefill_gsea_goBP_Ag1<<-NULL;nodefill_gsea_goMF_Ag1<<-NULL;nodefill_gsea_goCC_Ag1<<-NULL;nodefill_gsea_KEGG_Ag1<<-NULL;
	nodefill_gsta_goBP_Ag1<<-NULL;nodefill_gsta_goMF_Ag1<<-NULL;nodefill_gsta_goCC_Ag1<<-NULL;nodefill_gsta_KEGG_Ag1<<-NULL;
	genes_Ag1<<-NULL;ta_ag1_genes<<-NULL;myGraph_Ag1<<-NULL;ssize_Ag1<<-NULL;

	folder_Ag2<<-NULL;ann_Ag2<<-NULL;l_datAgTwo<<-NULL;datAgTwo2.m2<<-NULL;ta_ag2_norm2<<-NULL;samp_Ag2<<-NULL;
	fit2_Ag2<<-NULL;datAgTwo2.f3<<-NULL;ta_ag2_filt2<<-NULL;datAgTwo2.s3<<-NULL;ta_ag2_stat2<<-NULL;
	pca_Ag2<<-NULL;sample.clust_Ag2<<-NULL;DE_Ag2All<<-NULL;DE_Ag2_2<<-NULL;ta_ag2_dge2<<-NULL;clas_Ag2<<-NULL;
	GOresultBP_Ag2<<-NULL;ta_ag2_gsea_gobp<<-NULL;GOresultMF_Ag2<<-NULL;ta_ag2_gsea_gomf<<-NULL;
	GOresultCC_Ag2<<-NULL;ta_ag2_gsea_gocc<<-NULL;KEGGresult_Ag2<<-NULL;ta_ag2_gsea_kegg<<-NULL;
	GOtable.outBP_Ag2<<-NULL;ta_ag2_gsta_gobp<<-NULL;GOtable.outMF_Ag2<<-NULL;ta_ag2_gsta_gomf<<-NULL;
	GOtable.outCC_Ag2<<-NULL;ta_ag2_gsta_gocc<<-NULL;KEGGtable.out_Ag2<<-NULL;ta_ag2_gsta_kegg<<-NULL;
	graph_gsea_goBP_Ag2<<-NULL;ta_affy_legend_gsea_gobp<<-NULL;graph_gsea_goMF_Ag2<<-NULL;ta_affy_legend_gsea_gomf<<-NULL;
	graph_gsea_goCC_Ag2<<-NULL;ta_affy_legend_gsea_gocc<<-NULL;graph_gsea_KEGG_Ag2<<-NULL;ta_affy_legend_gsea_kegg<<-NULL;
	graph_gsta_goBP_Ag2<<-NULL;ta_affy_legend_gsta_gobp<<-NULL;graph_gsta_goMF_Ag2<<-NULL;ta_affy_legend_gsta_gomf<<-NULL;
	graph_gsta_goCC_Ag2<<-NULL;ta_affy_legend_gsta_gocc<<-NULL;graph_gsta_KEGG_Ag2<<-NULL;ta_affy_legend_gsta_kegg<<-NULL;
	legend_gsea_goBP_Ag2<<-NULL;legend_gsea_goMF_Ag2<<-NULL;legend_gsea_goCC_Ag2<<-NULL;legend_gsea_KEGG_Ag2<<-NULL;
	legend_gsta_goBP_Ag2<<-NULL;legend_gsta_goMF_Ag2<<-NULL;legend_gsta_goCC_Ag2<<-NULL;legend_gsta_KEGG_Ag2<<-NULL;
	nodefill_gsea_goBP_Ag2<<-NULL;nodefill_gsea_goMF_Ag2<<-NULL;nodefill_gsea_goCC_Ag2<<-NULL;nodefill_gsea_KEGG_Ag2<<-NULL;
	nodefill_gsta_goBP_Ag2<<-NULL;nodefill_gsta_goMF_Ag2<<-NULL;nodefill_gsta_goCC_Ag2<<-NULL;nodefill_gsta_KEGG_Ag2<<-NULL;
	genes_Ag2<<-NULL;ta_ag2_genes<<-NULL;myGraph_Ag2<<-NULL;ssize_Ag2<<-NULL;
	
	folder_Il_B<<-NULL;ann_Il_B<<-NULL;l_datIllBA<<-NULL;datIllBA2.m2<<-NULL;ta_ilb_norm2<<-NULL;samp_Il_B<<-NULL;
	fit2_Il_B<<-NULL;datIllBA2.f3<<-NULL;ta_ilb_filt2<<-NULL;datIllBA2.s3<<-NULL;ta_ilb_stat2<<-NULL;
	pca_Il_B<<-NULL;sample.clust_Il_B<<-NULL;DE_Il_BAll<<-NULL;DE_Il_B_2<<-NULL;ta_ilb_dge2<<-NULL;clas_Il_B<<-NULL;
	GOresultBP_Il_B<<-NULL;ta_ilb_gsea_gobp<<-NULL;GOresultMF_Il_B<<-NULL;ta_ilb_gsea_gomf<<-NULL;
	GOresultCC_Il_B<<-NULL;ta_ilb_gsea_gocc<<-NULL;KEGGresult_Il_B<<-NULL;ta_ilb_gsea_kegg<<-NULL;
	GOtable.outBP_Il_B<<-NULL;ta_ilb_gsta_gobp<<-NULL;GOtable.outMF_Il_B<<-NULL;ta_ilb_gsta_gomf<<-NULL;
	GOtable.outCC_Il_B<<-NULL;ta_ilb_gsta_gocc<<-NULL;KEGGtable.out_Il_B<<-NULL;ta_ilb_gsta_kegg<<-NULL;
	graph_gsea_goBP_Il_B<<-NULL;ta_affy_legend_gsea_gobp<<-NULL;graph_gsea_goMF_Il_B<<-NULL;ta_affy_legend_gsea_gomf<<-NULL;
	graph_gsea_goCC_Il_B<<-NULL;ta_affy_legend_gsea_gocc<<-NULL;graph_gsea_KEGG_Il_B<<-NULL;ta_affy_legend_gsea_kegg<<-NULL;
	graph_gsta_goBP_Il_B<<-NULL;ta_affy_legend_gsta_gobp<<-NULL;graph_gsta_goMF_Il_B<<-NULL;ta_affy_legend_gsta_gomf<<-NULL;
	graph_gsta_goCC_Il_B<<-NULL;ta_affy_legend_gsta_gocc<<-NULL;graph_gsta_KEGG_Il_B<<-NULL;ta_affy_legend_gsta_kegg<<-NULL;
	legend_gsea_goBP_Il_B<<-NULL;legend_gsea_goMF_Il_B<<-NULL;legend_gsea_goCC_Il_B<<-NULL;legend_gsea_KEGG_Il_B<<-NULL;
	legend_gsta_goBP_Il_B<<-NULL;legend_gsta_goMF_Il_B<<-NULL;legend_gsta_goCC_Il_B<<-NULL;legend_gsta_KEGG_Il_B<<-NULL;
	nodefill_gsea_goBP_Il_B<<-NULL;nodefill_gsea_goMF_Il_B<<-NULL;nodefill_gsea_goCC_Il_B<<-NULL;nodefill_gsea_KEGG_Il_B<<-NULL;
	nodefill_gsta_goBP_Il_B<<-NULL;nodefill_gsta_goMF_Il_B<<-NULL;nodefill_gsta_goCC_Il_B<<-NULL;nodefill_gsta_KEGG_Il_B<<-NULL;
	genes_Il_B<<-NULL;ta_ilb_genes<<-NULL;myGraph_Il_B<<-NULL;ssize_Il_B<<-NULL;
	
	folder_Il_L<<-NULL;ann_Il_L<<-NULL;l_lumi_data<<-NULL;lumi_NQ.m2<<-NULL;ta_ill_norm2<<-NULL;samp_Il_L<<-NULL;
	fit2_Il_L<<-NULL;lumi_NQ.f3<<-NULL;ta_ill_filt2<<-NULL;lumi_NQ.s3<<-NULL;ta_ill_stat2<<-NULL;
	pca_Il_L<<-NULL;sample.clust_Il_L<<-NULL;DE_Il_LAll<<-NULL;DE_Il_L_2<<-NULL;ta_ill_dge2<<-NULL;clas_Il_L<<-NULL;
	GOresultBP_Il_L<<-NULL;ta_ill_gsea_gobp<<-NULL;GOresultMF_Il_L<<-NULL;ta_ill_gsea_gomf<<-NULL;
	GOresultCC_Il_L<<-NULL;ta_ill_gsea_gocc<<-NULL;KEGGresult_Il_L<<-NULL;ta_ill_gsea_kegg<<-NULL;
	GOtable.outBP_Il_L<<-NULL;ta_ill_gsta_gobp<<-NULL;GOtable.outMF_Il_L<<-NULL;ta_ill_gsta_gomf<<-NULL;
	GOtable.outCC_Il_L<<-NULL;ta_ill_gsta_gocc<<-NULL;KEGGtable.out_Il_L<<-NULL;ta_ill_gsta_kegg<<-NULL;
	graph_gsea_goBP_Il_L<<-NULL;ta_affy_legend_gsea_gobp<<-NULL;graph_gsea_goMF_Il_L<<-NULL;ta_affy_legend_gsea_gomf<<-NULL;
	graph_gsea_goCC_Il_L<<-NULL;ta_affy_legend_gsea_gocc<<-NULL;graph_gsea_KEGG_Il_L<<-NULL;ta_affy_legend_gsea_kegg<<-NULL;
	graph_gsta_goBP_Il_L<<-NULL;ta_affy_legend_gsta_gobp<<-NULL;graph_gsta_goMF_Il_L<<-NULL;ta_affy_legend_gsta_gomf<<-NULL;
	graph_gsta_goCC_Il_L<<-NULL;ta_affy_legend_gsta_gocc<<-NULL;graph_gsta_KEGG_Il_L<<-NULL;ta_affy_legend_gsta_kegg<<-NULL;
	legend_gsea_goBP_Il_L<<-NULL;legend_gsea_goMF_Il_L<<-NULL;legend_gsea_goCC_Il_L<<-NULL;legend_gsea_KEGG_Il_L<<-NULL;
	legend_gsta_goBP_Il_L<<-NULL;legend_gsta_goMF_Il_L<<-NULL;legend_gsta_goCC_Il_L<<-NULL;legend_gsta_KEGG_Il_L<<-NULL;
	nodefill_gsea_goBP_Il_L<<-NULL;nodefill_gsea_goMF_Il_L<<-NULL;nodefill_gsea_goCC_Il_L<<-NULL;nodefill_gsea_KEGG_Il_L<<-NULL;
	nodefill_gsta_goBP_Il_L<<-NULL;nodefill_gsta_goMF_Il_L<<-NULL;nodefill_gsta_goCC_Il_L<<-NULL;nodefill_gsta_KEGG_Il_L<<-NULL;
	genes_Il_L<<-NULL;ta_ill_genes<<-NULL;myGraph_Il_L<<-NULL;ssize_Il_L<<-NULL;
	
	folder_N<<-NULL;ann_N<<-NULL;l_data.matrix_Nimblegen<<-NULL;data.matrix_Nimblegen2.m2<<-NULL;ta_nbl_norm2<<-NULL;samp_N<<-NULL;
	fit2_N<<-NULL;data.matrix_Nimblegen2.f3<<-NULL;ta_nbl_filt2<<-NULL;data.matrix_Nimblegen2.s3<<-NULL;ta_nbl_stat2<<-NULL;
	GOresultBP_N<<-NULL;ta_nbl_gsea_gobp<<-NULL;GOresultMF_N<<-NULL;ta_nbl_gsea_gomf<<-NULL;
	GOresultCC_N<<-NULL;ta_nbl_gsea_gocc<<-NULL;KEGGresult_N<<-NULL;ta_nbl_gsea_kegg<<-NULL;
	pca_N<<-NULL;sample.clust_N<<-NULL;DE_NAll<<-NULL;DE_N_2<<-NULL;ta_nbl_dge2<<-NULL;clas_N<<-NULL;
	GOtable.outBP_N<<-NULL;ta_nbl_gsta_gobp<<-NULL;GOtable.outMF_N<<-NULL;ta_nbl_gsta_gomf<<-NULL;
	GOtable.outCC_N<<-NULL;ta_nbl_gsta_gocc<<-NULL;KEGGtable.out_N<<-NULL;ta_nbl_gsta_kegg<<-NULL;
	graph_gsea_goBP_N<<-NULL;ta_affy_legend_gsea_gobp<<-NULL;graph_gsea_goMF_N<<-NULL;ta_affy_legend_gsea_gomf<<-NULL;
	graph_gsea_goCC_N<<-NULL;ta_affy_legend_gsea_gocc<<-NULL;graph_gsea_KEGG_N<<-NULL;ta_affy_legend_gsea_kegg<<-NULL;
	graph_gsta_goBP_N<<-NULL;ta_affy_legend_gsta_gobp<<-NULL;graph_gsta_goMF_N<<-NULL;ta_affy_legend_gsta_gomf<<-NULL;
	graph_gsta_goCC_N<<-NULL;ta_affy_legend_gsta_gocc<<-NULL;graph_gsta_KEGG_N<<-NULL;ta_affy_legend_gsta_kegg<<-NULL;
	legend_gsea_goBP_N<<-NULL;legend_gsea_goMF_N<<-NULL;legend_gsea_goCC_N<<-NULL;legend_gsea_KEGG_N<<-NULL;
	legend_gsta_goBP_N<<-NULL;legend_gsta_goMF_N<<-NULL;legend_gsta_goCC_N<<-NULL;legend_gsta_KEGG_N<<-NULL;
	nodefill_gsea_goBP_N<<-NULL;nodefill_gsea_goMF_N<<-NULL;nodefill_gsea_goCC_N<<-NULL;nodefill_gsea_KEGG_N<<-NULL;
	nodefill_gsta_goBP_N<<-NULL;nodefill_gsta_goMF_N<<-NULL;nodefill_gsta_goCC_N<<-NULL;nodefill_gsta_KEGG_N<<-NULL;
	genes_N<<-NULL;ta_nbl_genes<<-NULL;myGraph_N<<-NULL;ssize_N<<-NULL;
	
	folder_S<<-NULL;ann_S<<-NULL;l_data.matrix_series<<-NULL;l_data.matrixLog<<-NULL;l_data.matrixImp<<-NULL;data.matrixNorm.m2<<-NULL;ta_smt_norm2<<-NULL;
	samp_S<<-NULL;fit2_S<<-NULL;data.matrixNorm.f3<<-NULL;ta_smt_filt2<<-NULL;data.matrixNorm.s3<<-NULL;ta_smt_stat2<<-NULL;
	pca_S<<-NULL;sample.clust_S<<-NULL;DE_SAll<<-NULL;DE_S_2<<-NULL;ta_smt_dge2<<-NULL;clas_S<<-NULL;
	GOresultBP_S<<-NULL;ta_smt_gsea_gobp<<-NULL;GOresultMF_S<<-NULL;ta_smt_gsea_gomf<<-NULL;
	GOresultCC_S<<-NULL;ta_smt_gsea_gocc<<-NULL;KEGGresult_S<<-NULL;ta_smt_gsea_kegg<<-NULL;
	GOtable.outBP_S<<-NULL;ta_smt_gsta_gobp<<-NULL;GOtable.outMF_S<<-NULL;ta_smt_gsta_gomf<<-NULL;
	GOtable.outCC_S<<-NULL;ta_smt_gsta_gocc<<-NULL;KEGGtable.out_S<<-NULL;ta_smt_gsta_kegg<<-NULL;
	graph_gsea_goBP_S<<-NULL;ta_affy_legend_gsea_gobp<<-NULL;graph_gsea_goMF_S<<-NULL;ta_affy_legend_gsea_gomf<<-NULL;
	graph_gsea_goCC_S<<-NULL;ta_affy_legend_gsea_gocc<<-NULL;graph_gsea_KEGG_S<<-NULL;ta_affy_legend_gsea_kegg<<-NULL;
	graph_gsta_goBP_S<<-NULL;ta_affy_legend_gsta_gobp<<-NULL;graph_gsta_goMF_S<<-NULL;ta_affy_legend_gsta_gomf<<-NULL;
	graph_gsta_goCC_S<<-NULL;ta_affy_legend_gsta_gocc<<-NULL;graph_gsta_KEGG_S<<-NULL;ta_affy_legend_gsta_kegg<<-NULL;
	legend_gsea_goBP_S<<-NULL;legend_gsea_goMF_S<<-NULL;legend_gsea_goCC_S<<-NULL;legend_gsea_KEGG_S<<-NULL;
	legend_gsta_goBP_S<<-NULL;legend_gsta_goMF_S<<-NULL;legend_gsta_goCC_S<<-NULL;legend_gsta_KEGG_S<<-NULL;
	nodefill_gsea_goBP_S<<-NULL;nodefill_gsea_goMF_S<<-NULL;nodefill_gsea_goCC_S<<-NULL;nodefill_gsea_KEGG_S<<-NULL;
	nodefill_gsta_goBP_S<<-NULL;nodefill_gsta_goMF_S<<-NULL;nodefill_gsta_goCC_S<<-NULL;nodefill_gsta_KEGG_S<<-NULL;
	genes_S<<-NULL;ta_smt_genes<<-NULL;myGraph_S<<-NULL;ssize_S<<-NULL;
	
	folder_O<<-NULL;ann_O<<-NULL;l_data.matrix_online<<-NULL;l_data.matrix_onlineLog<<-NULL;l_data.matrix_onlineImp<<-NULL;data.matrix_onlineNorm.m2<<-NULL;
	ta_onl_norm2<<-NULL;samp_O<<-NULL;fit2_O<<-NULL;data.matrix_onlineNorm.f3<<-NULL;ta_onl_filt2<<-NULL;data.matrix_onlineNorm.s3<<-NULL;ta_onl_stat2<<-NULL;
	pca_O<<-NULL;sample.clust_O<<-NULL;DE_OAll<<-NULL;DE_O_2<<-NULL;ta_onl_dge2<<-NULL;clas_O<<-NULL;
	GOresultBP_O<<-NULL;ta_onl_gsea_gobp<<-NULL;GOresultMF_O<<-NULL;ta_onl_gsea_gomf<<-NULL;
	GOresultCC_O<<-NULL;ta_onl_gsea_gocc<<-NULL;KEGGresult_O<<-NULL;ta_onl_gsea_kegg<<-NULL;
	GOtable.outBP_O<<-NULL;ta_onl_gsta_gobp<<-NULL;GOtable.outMF_O<<-NULL;ta_onl_gsta_gomf<<-NULL;
	GOtable.outCC_O<<-NULL;ta_onl_gsta_gocc<<-NULL;KEGGtable.out_O<<-NULL;ta_onl_gsta_kegg<<-NULL;
	graph_gsea_goBP_O<<-NULL;ta_affy_legend_gsea_gobp<<-NULL;graph_gsea_goMF_O<<-NULL;ta_affy_legend_gsea_gomf<<-NULL;
	graph_gsea_goCC_O<<-NULL;ta_affy_legend_gsea_gocc<<-NULL;graph_gsea_KEGG_O<<-NULL;ta_affy_legend_gsea_kegg<<-NULL;
	graph_gsta_goBP_O<<-NULL;ta_affy_legend_gsta_gobp<<-NULL;graph_gsta_goMF_O<<-NULL;ta_affy_legend_gsta_gomf<<-NULL;
	graph_gsta_goCC_O<<-NULL;ta_affy_legend_gsta_gocc<<-NULL;graph_gsta_KEGG_O<<-NULL;ta_affy_legend_gsta_kegg<<-NULL;
	legend_gsea_goBP_O<<-NULL;legend_gsea_goMF_O<<-NULL;legend_gsea_goCC_O<<-NULL;legend_gsea_KEGG_O<<-NULL;
	legend_gsta_goBP_O<<-NULL;legend_gsta_goMF_O<<-NULL;legend_gsta_goCC_O<<-NULL;legend_gsta_KEGG_O<<-NULL;
	nodefill_gsea_goBP_O<<-NULL;nodefill_gsea_goMF_O<<-NULL;nodefill_gsea_goCC_O<<-NULL;nodefill_gsea_KEGG_O<<-NULL;
	nodefill_gsta_goBP_O<<-NULL;nodefill_gsta_goMF_O<<-NULL;nodefill_gsta_goCC_O<<-NULL;nodefill_gsta_KEGG_O<<-NULL;
	genes_O<<-NULL;ta_onl_genes<<-NULL;myGraph_O<<-NULL;ssize_O<<-NULL;

	heatcol=NULL
	heatcol<<-colorRampPalette(c("Green","Red"))(32)
	cur_dir<-getwd();

	tkadd(ma_menubar,"cascade",label="File",menu=ma_filemenu)
	tkadd(ma_filemenu,"command",label="Open",command=function(){
		openfile<-tkmessageBox(title="Confirm",message="Data tree will not be available for this..!",icon="question",type="okcancel")
		if(tclvalue(openfile)=="ok"){
			file<-tclvalue(tkgetOpenFile(title="Select the file"))
			if(!is.na(file) & length(grep(".Rdata",file))!=0){
				load(file,.GlobalEnv)
			} else {
				tkmessageBox(title="Error",message="Could not load this type of file!",icon="error",type="ok")
			}
		}	
		on.exit(setwd(cur_dir))
	})
	ma_load<-tkmenu(ma_filemenu)
	tkadd(ma_filemenu,"cascade",label="Load",menu=ma_load)
	tkadd(ma_load,"command",label="Affymetrix",command=function(){
		setwd(cur_dir)
		code<-system.file("extdata","affym2.R",package="maGUI")
		source(code)
	})
	tkadd(ma_load,"command",label="Agilent-OneColor",command=function(){
		setwd(cur_dir)
		code<-system.file("extdata","agone2.R",package="maGUI")
		source(code)
	})
	tkadd(ma_load,"command",label="Agilent-TwoColor",command=function(){
		setwd(cur_dir)
		code<-system.file("extdata","agtwo2.R",package="maGUI")
		source(code)
	})
	tkadd(ma_load,"command",label="Illumina-BeadArray",command=function(){
		setwd(cur_dir)
		code<-system.file("extdata","illbead2.R",package="maGUI")
		source(code)
	})
	tkadd(ma_load,"command",label="Illumina-Lumi",command=function(){
		setwd(cur_dir)
		code<-system.file("extdata","illlumi2.R",package="maGUI")
		source(code)
	})
	tkadd(ma_load,"command",label="Nimblegen",command=function(){
		setwd(cur_dir)
		code<-system.file("extdata","nimblg2.R",package="maGUI")
		source(code)
	})
	tkadd(ma_load,"command",label="Series-Matrix",command=function(){
		setwd(cur_dir)
		code<-system.file("extdata","dmsm2.R",package="maGUI")
		source(code)
	})
	tkadd(ma_load,"command",label="Online-Data",command=function(){
		setwd(cur_dir)
		code<-system.file("extdata","dmo2.R",package="maGUI")
		source(code)
	})
	tkadd(ma_filemenu,"command",label="Save",command=function(){
		w_imp1<-tktoplevel()
		tkwm.title(w_imp1,"Save")
		tkwm.resizable(w_imp1,0,0)
		frame1_imp1<-ttkframe(w_imp1,padding=c(3,3,12,12))
		tkpack(ttklabel(frame1_imp1,text='Give a name:'),side="left",padx=12)
		exp_file<-tclVar("")
		c1<-ttkentry(frame1_imp1,textvariable=exp_file,width=25)
		tkpack(c1,side="left",anchor="e")
		tkpack(frame1_imp1,expand=TRUE,fill="both",side="top")
		frame2_imp1<-ttkframe(w_imp1,padding=c(3,3,12,12))
		r_but1<-ttkbutton(frame2_imp1,text="Ok")
		tkpack(r_but1,side="top",anchor="e",pady=5)
		tkpack(frame2_imp1,expand=TRUE,fill="both",side="top")
		tkconfigure(r_but1,command=function(){
			tkwm.withdraw(w_imp1)
			out_name<-paste(tclvalue(exp_file),"Rdata",sep=".")
			folder<-tclvalue(tkchooseDirectory(title="Destination Folder"))
			setwd(folder)
			save.image(out_name)
		})
		on.exit(setwd(cur_dir))	
	})
	tkadd(ma_filemenu,"command",label="Quit",command=function(){
		exit<-tkmessageBox(title="Confirm",message="Really quit!",icon="question",type="okcancel")
		if(tclvalue(exit)=="ok"){
			on.exit(setwd(cur_dir))
			tkdestroy(ma_w)
		}
	})

	ma_prepmenu<-tkmenu(ma_menubar)
	tkadd(ma_menubar,"cascade",label="Pre-processing",menu=ma_prepmenu)
	tkadd(ma_prepmenu,"command",label="Log_Transformation",command=function(){
		setwd(cur_dir)
		code<-system.file("extdata","prep_log2.R",package="maGUI")
		source(code)	
	})
	tkadd(ma_prepmenu,"command",label="KNN_Imputation",command=function(){
		setwd(cur_dir)
		code<-system.file("extdata","prep_knn2.R",package="maGUI")
		source(code)	
	})
	tkadd(ma_prepmenu,"command",label="Normalization",command=function(){
		setwd(cur_dir)
		code<-system.file("extdata","normlz2.R",package="maGUI")
		source(code)	
	})
	tkadd(ma_prepmenu,"command",label="Quality_Control",command=function(){
		setwd(cur_dir)
		code<-system.file("extdata","qlchk2.R",package="maGUI")
		source(code)	
	})

	ma_analzmenu<-tkmenu(ma_menubar)
	tkadd(ma_menubar,"cascade",label="Analysis",menu=ma_analzmenu)
	ma_filt<-tkmenu(ma_analzmenu)
	tkadd(ma_analzmenu,"cascade",label="Filtering_Statistical_Significant",menu=ma_filt)
	tkadd(ma_filt,"command",label="Specific",command=function(){
		setwd(cur_dir)
		code<-system.file("extdata","filter_sp2.R",package="maGUI")
		source(code)	
	})
	tkadd(ma_filt,"command",label="Un-specific",command=function(){
		setwd(cur_dir)
		code<-system.file("extdata","filter_unsp2.R",package="maGUI")
		source(code)	
	})
	tkadd(ma_analzmenu,"command",label="Differential_Gene_Expression",command=function(){
		setwd(cur_dir)
		code<-system.file("extdata","dge2.R",package="maGUI")
		source(code)	
	})
	tkadd(ma_analzmenu,"command",label="Principal_Component_Analysis",command=function(){
		setwd(cur_dir)
		code<-system.file("extdata","pca2.R",package="maGUI")
		source(code)	
	})
	tkadd(ma_analzmenu,"command",label="Clustering_Visualization",command=function(){
		setwd(cur_dir)
		code<-system.file("extdata","cluster2.R",package="maGUI")
		source(code)	
	})
	tkadd(ma_analzmenu,"command",label="Classification_Visualization",command=function(){
		setwd(cur_dir)
		code<-system.file("extdata","class2.R",package="maGUI")
		source(code)	
	})

	ma_misclmenu<-tkmenu(ma_menubar)
	tkadd(ma_menubar,"cascade",label="Miscellaneous",menu=ma_misclmenu)
	ma_gsea<-tkmenu(ma_misclmenu)
	tkadd(ma_misclmenu,"cascade",label="Gene_Set_Enrichment_Analysis",menu=ma_gsea)
	tkadd(ma_gsea,"command",label="GO_Biological_Process",command=function(){
		setwd(cur_dir)
		code<-system.file("extdata","gsea_gobp2.R",package="maGUI")
		source(code)
	})
	tkadd(ma_gsea,"command",label="GO_Molecular_Function",command=function(){
		setwd(cur_dir)
		code<-system.file("extdata","gsea_gomf2.R",package="maGUI")
		source(code)
	})
	tkadd(ma_gsea,"command",label="GO_Cellular_Component",command=function(){
		setwd(cur_dir)
		code<-system.file("extdata","gsea_gocc2.R",package="maGUI")
		source(code)
	})
	tkadd(ma_gsea,"command",label="KEGG_Pathways",command=function(){
		setwd(cur_dir)
		code<-system.file("extdata","gsea_kegg2.R",package="maGUI")
		source(code)
	})
	ma_gsta<-tkmenu(ma_misclmenu)
	tkadd(ma_misclmenu,"cascade",label="Gene_Set_Test_Analysis",menu=ma_gsta)
	tkadd(ma_gsta,"command",label="GO_Biological_Process",command=function(){
		setwd(cur_dir)
		code<-system.file("extdata","gsta_gobp2.R",package="maGUI")
		source(code)
	})
	tkadd(ma_gsta,"command",label="GO_Molecular_Function",command=function(){
		setwd(cur_dir)
		code<-system.file("extdata","gsta_gomf2.R",package="maGUI")
		source(code)
	})
	tkadd(ma_gsta,"command",label="GO_Cellular_Component",command=function(){
		setwd(cur_dir)
		code<-system.file("extdata","gsta_gocc2.R",package="maGUI")
		source(code)
	})
	tkadd(ma_gsta,"command",label="KEGG_Pathways",command=function(){
		setwd(cur_dir)
		code<-system.file("extdata","gsta_kegg2.R",package="maGUI")
		source(code)
	})
	ma_ggsea<-tkmenu(ma_misclmenu)
	tkadd(ma_misclmenu,"cascade",label="Graph_GSEA",menu=ma_ggsea)
	tkadd(ma_ggsea,"command",label="GO_Biological_Process",command=function(){
		setwd(cur_dir)
		code<-system.file("extdata","graph_gsea_gobp2.R",package="maGUI")
		source(code)
	})
	tkadd(ma_ggsea,"command",label="GO_Molecular_Function",command=function(){
		setwd(cur_dir)
		code<-system.file("extdata","graph_gsea_gomf2.R",package="maGUI")
		source(code)
	})
	tkadd(ma_ggsea,"command",label="GO_Cellular_Component",command=function(){
		setwd(cur_dir)
		code<-system.file("extdata","graph_gsea_gocc2.R",package="maGUI")
		source(code)
	})
	tkadd(ma_ggsea,"command",label="KEGG_Pathways",command=function(){
		setwd(cur_dir)
		code<-system.file("extdata","graph_gsea_kegg2.R",package="maGUI")
		source(code)
	})
	ma_ggsta<-tkmenu(ma_misclmenu)
	tkadd(ma_misclmenu,"cascade",label="Graph_GSTA",menu=ma_ggsta)
	tkadd(ma_ggsta,"command",label="GO_Biological_Process",command=function(){
		setwd(cur_dir)
		code<-system.file("extdata","graph_gsta_gobp2.R",package="maGUI")
		source(code)
	})
	tkadd(ma_ggsta,"command",label="GO_Molecular_Function",command=function(){
		setwd(cur_dir)
		code<-system.file("extdata","graph_gsta_gomf2.R",package="maGUI")
		source(code)
	})
	tkadd(ma_ggsta,"command",label="GO_Cellular_Component",command=function(){
		setwd(cur_dir)
		code<-system.file("extdata","graph_gsta_gocc2.R",package="maGUI")
		source(code)
	})
	tkadd(ma_ggsta,"command",label="KEGG_Pathways",command=function(){
		setwd(cur_dir)
		code<-system.file("extdata","graph_gsta_kegg2.R",package="maGUI")
		source(code)
	})
	tkadd(ma_misclmenu,"command",label="Gene_Symbol",command=function(){
		setwd(cur_dir)
		code<-system.file("extdata","symbol2.R",package="maGUI")
		source(code)
	})
	tkadd(ma_misclmenu,"command",label="Co-expression_Network",command=function(){
		setwd(cur_dir)
		code<-system.file("extdata","ntwk2.R",package="maGUI")
		source(code)
	})
	tkadd(ma_misclmenu,"command",label="Sample_Size_Estimation",command=function(){
		setwd(cur_dir)
		code<-system.file("extdata","sse2.R",package="maGUI")
		source(code)
	})

	ma_expomenu<-tkmenu(ma_menubar)
	tkadd(ma_menubar,"cascade",label="Export",menu=ma_expomenu)
	tkadd(ma_expomenu,"command",label="Normalized_Data",command=function(){
		ma_export("Normalized_Data")
	})
	tkadd(ma_expomenu,"command",label="QC_Plot",command=function(){
		ma_export("QC_Plot")
	})
	tkadd(ma_expomenu,"command",label="Filtered_Data",command=function(){
		ma_export("Filtered_Data")
	})
	tkadd(ma_expomenu,"command",label="Stat_Sign_Data",command=function(){
		ma_export("Stat_Sign_Data")
	})
	tkadd(ma_expomenu,"command",label="DGE_Data",command=function(){
		ma_export("DGE_Data")
	})
	tkadd(ma_expomenu,"command",label="PCA_Data",command=function(){
		ma_export("PCA_Data")
	})
	tkadd(ma_expomenu,"command",label="Clustered_Data",command=function(){
		ma_export("Clustered_Data")
	})
	tkadd(ma_expomenu,"command",label="Classification_Data",command=function(){
		ma_export("Classification_Data")
	})
	ma_gsea_expo<-tkmenu(ma_expomenu)
	tkadd(ma_expomenu,"cascade",label="GSEA_Data",menu=ma_gsea_expo)
	tkadd(ma_gsea_expo,"command",label="GO_BP",command=function(){
		ma_export("GSEA_Data_GO_BP")
	})
	tkadd(ma_gsea_expo,"command",label="GO_MF",command=function(){
		ma_export("GSEA_Data_GO_MF")
	})
	tkadd(ma_gsea_expo,"command",label="GO_CC",command=function(){
		ma_export("GSEA_Data_GO_CC")
	})
	tkadd(ma_gsea_expo,"command",label="KEGG_Pathways",command=function(){
		ma_export("GSEA_Data_KEGG_Pathways")
	})
	ma_gsta_expo<-tkmenu(ma_expomenu)
	tkadd(ma_expomenu,"cascade",label="GSTA_Data",menu=ma_gsta_expo)
	tkadd(ma_gsta_expo,"command",label="GO_BP",command=function(){
		ma_export("GSTA_Data_GO_BP")
	})
	tkadd(ma_gsta_expo,"command",label="GO_MF",command=function(){
		ma_export("GSTA_Data_GO_MF")
	})
	tkadd(ma_gsta_expo,"command",label="GO_CC",command=function(){
		ma_export("GSTA_Data_GO_CC")
	})
	tkadd(ma_gsta_expo,"command",label="KEGG_Pathways",command=function(){
		ma_export("GSTA_Data_KEGG_Pathways")
	})
	ma_ggsea_expo<-tkmenu(ma_expomenu)
	tkadd(ma_expomenu,"cascade",label="Graph_GSEA_Data",menu=ma_ggsea_expo)
	tkadd(ma_ggsea_expo,"command",label="GO_BP",command=function(){
		ma_export("Graph_GSEA_Data_GO_BP")
	})
	tkadd(ma_ggsea_expo,"command",label="GO_MF",command=function(){
		ma_export("Graph_GSEA_Data_GO_MF")
	})
	tkadd(ma_ggsea_expo,"command",label="GO_CC",command=function(){
		ma_export("Graph_GSEA_Data_GO_CC")
	})
	tkadd(ma_ggsea_expo,"command",label="KEGG_Pathways",command=function(){
		ma_export("Graph_GSEA_Data_KEGG_Pathways")
	})
	ma_ggsta_expo<-tkmenu(ma_expomenu)
	tkadd(ma_expomenu,"cascade",label="Graph_GSTA_Data",menu=ma_ggsta_expo)
	tkadd(ma_ggsta_expo,"command",label="GO_BP",command=function(){
		ma_export("Graph_GSTA_Data_GO_BP")
	})
	tkadd(ma_ggsta_expo,"command",label="GO_MF",command=function(){
		ma_export("Graph_GSTA_Data_GO_MF")
	})
	tkadd(ma_ggsta_expo,"command",label="GO_CC",command=function(){
		ma_export("Graph_GSTA_Data_GO_CC")
		})
	tkadd(ma_ggsta_expo,"command",label="KEGG_Pathways",command=function(){
		ma_export("Graph_GSTA_Data_KEGG_Pathways")
	})
	tkadd(ma_expomenu,"command",label="Gene_Symbol_Data",command=function(){
		ma_export("Gene_Symbol_Data")
	})
	tkadd(ma_expomenu,"command",label="Co-expression_Network_Data",command=function(){
		ma_export("Co-expression_Network_Data")
	})
	tkadd(ma_expomenu,"command",label="SSE_Data",command=function(){
		ma_export("SSE_Data")
	})

	ma_helpmenu<-tkmenu(ma_menubar)
	tkadd(ma_menubar,"cascade",label="Help",menu=ma_helpmenu)
	tkadd(ma_helpmenu,"command",label="About_maGUI",command=function(){
		tkmessageBox(title="About maGUI",message="This is maGUI version 4.0 developed and produced by Dhammapal Bharne. It can analyze and annotate microarray data of different platforms",icon="info")
	})
	tkadd(ma_helpmenu,"command",label="maGUI_Help",command=function(){
		openPDF("http://bif.uohyd.ac.in/maGUI/maGUI_Help.pdf")
	})
	tkadd(ma_helpmenu,"command",label="maGUI_Manual",command=function(){
		openPDF("https://cran.r-project.org/web/packages/maGUI/maGUI.pdf")
	})
	tkadd(ma_helpmenu,"command",label="maGUI_Tutorial_Doc",command=function(){
		browseURL("https://www.researchgate.net/publication/344717933_maGUI_Tutorialpdf")
	})
	tkadd(ma_helpmenu,"command",label="maGUI_Tutorial_Video",command=function(){
		browseURL("https://www.youtube.com/watch?v=vzaoMlNOGKE")
	})
	tkadd(ma_helpmenu,"command",label="maGUI_References",command=function(){
		w_imp1<-tktoplevel()
		tkwm.title(w_imp1,"References")
		tkwm.resizable(w_imp1,0,0)
		frame1_imp1<-ttkframe(w_imp1,padding=c(3,3,12,12))
		tkpack(ttklabel(frame1_imp1,text='1. Bharne D, Kant P, Vindal V. \n    maGUI: A Graphical User Interface for Analysis and Annotation of DNA Microarray Data. \n    The Open Bioinformatics Journal. 2019 Jun 30;12(1).'),side="left",padx=12)
		tkpack(frame1_imp1,expand=TRUE,fill="both",side="top")
		frame2_imp1<-ttkframe(w_imp1,padding=c(3,3,12,12))
		tkpack(ttklabel(frame2_imp1,text='2. Lawrence MF, Verzani J. \n    Programming Graphical User Interfaces in R. \n    CRC Press, Taylor & Francis Group. 2012.'),side="left",padx=12)
		tkpack(frame2_imp1,expand=TRUE,fill="both",side="top")
		frame3_imp1<-ttkframe(w_imp1,padding=c(3,3,12,12))
		tkpack(ttklabel(frame3_imp1,text='3. Tuimala J. \n    DNA microarray data analysis using Bioconductor.   \n    The Finnish IT center for Science CSC. 2008.'),side="left",padx=12)
		tkpack(frame3_imp1,expand=TRUE,fill="both",side="top")
		frame4_imp1<-ttkframe(w_imp1,padding=c(3,3,12,12))
		r_but1<-ttkbutton(frame4_imp1,text="Ok")
		tkpack(r_but1,side="top",anchor="e",pady=5)
		tkpack(frame4_imp1,expand=TRUE,fill="both",side="top")
		tkconfigure(r_but1,command=function(){
			tkwm.withdraw(w_imp1)
		})
		on.exit(setwd(cur_dir))			
	})
	tkadd(ma_helpmenu,"command",label="maGUI_Citation",command=function(){
		tkmessageBox(title="Cite maGUI",message="Dhammapal Bharne, Praveen Kant, Vaibhav Vindal. maGUI: A Graphical User Interface for Analysis and Annotation of DNA Microarray Data. The Open Bioinformatics Journal. 2019; 12:40-44. URL https://benthamopen.com/FULLTEXT/TOBIOIJ-12-40.",icon="info")
	})
	tkadd(ma_helpmenu,"command",label="Contact",command=function(){
		tkmessageBox(title="Contact",message="dhammapalb@gmail.com",icon="info")
	})

	tclRequire("Tktable")
	code<-system.file("extdata","display2.R",package="maGUI")
	source(code)
	code<-system.file("extdata","display_mod2.R",package="maGUI")
	source(code)
	code<-system.file("extdata","export2.R",package="maGUI")
	source(code)

}
